SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS `direct_fees_installments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(191) NOT NULL,
  `fees_master_id` int(11) NOT NULL,
  `percentange` double(8,2) NOT NULL,
  `amount` double(8,2) NOT NULL,
  `due_date` date NOT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `direct_fees_installments_school_id_foreign` (`school_id`),
  CONSTRAINT `direct_fees_installments_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `direct_fees_installment_assigns` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fees_installment_id` int(11) NOT NULL,
  `fees_master_ids` text DEFAULT NULL,
  `amount` double(10,2) DEFAULT NULL,
  `paid_amount` double(10,2) DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `payment_mode` varchar(100) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `slip` varchar(191) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 0,
  `assign_ids` text DEFAULT NULL,
  `bank_id` int(10) unsigned DEFAULT NULL,
  `discount_amount` double(10,2) DEFAULT 0.00,
  `fees_discount_id` int(10) unsigned DEFAULT NULL,
  `fees_type_id` int(10) unsigned DEFAULT NULL,
  `student_id` int(10) unsigned DEFAULT NULL,
  `record_id` int(10) unsigned DEFAULT NULL,
  `collected_by` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `created_by` int(10) unsigned DEFAULT NULL,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `direct_fees_installment_assigns_bank_id_foreign` (`bank_id`),
  KEY `direct_fees_installment_assigns_fees_discount_id_foreign` (`fees_discount_id`),
  KEY `direct_fees_installment_assigns_fees_type_id_foreign` (`fees_type_id`),
  KEY `direct_fees_installment_assigns_student_id_foreign` (`student_id`),
  KEY `direct_fees_installment_assigns_school_id_foreign` (`school_id`),
  CONSTRAINT `direct_fees_installment_assigns_bank_id_foreign` FOREIGN KEY (`bank_id`) REFERENCES `sm_bank_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `direct_fees_installment_assigns_fees_discount_id_foreign` FOREIGN KEY (`fees_discount_id`) REFERENCES `sm_fees_discounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `direct_fees_installment_assigns_fees_type_id_foreign` FOREIGN KEY (`fees_type_id`) REFERENCES `sm_fees_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `direct_fees_installment_assigns_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `direct_fees_installment_assigns_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `sm_students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `direct_fees_reminders` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `due_date_before` int(11) NOT NULL,
  `notification_types` varchar(191) NOT NULL,
  `academic_id` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `direct_fees_reminders_school_id_foreign` (`school_id`),
  CONSTRAINT `direct_fees_reminders_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `direct_fees_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fees_installment` tinyint(1) NOT NULL DEFAULT 0,
  `fees_reminder` tinyint(1) NOT NULL DEFAULT 0,
  `reminder_before` int(11) NOT NULL DEFAULT 5,
  `no_installment` int(11) NOT NULL DEFAULT 0,
  `due_date_from_sem` int(11) NOT NULL DEFAULT 10,
  `end_day` int(11) DEFAULT NULL,
  `academic_id` int(10) unsigned DEFAULT NULL,
  `school_id` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `direct_fees_settings_school_id_foreign` (`school_id`),
  CONSTRAINT `direct_fees_settings_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `dire_fees_installment_child_payments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `direct_fees_installment_assign_id` int(11) NOT NULL,
  `invoice_no` int(11) NOT NULL DEFAULT 1,
  `amount` double(10,2) DEFAULT NULL,
  `paid_amount` double(10,2) DEFAULT NULL,
  `balance_amount` double(10,2) DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `payment_mode` varchar(100) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `slip` varchar(191) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 0,
  `bank_id` int(10) unsigned DEFAULT NULL,
  `discount_amount` double(10,2) DEFAULT 0.00,
  `fees_type_id` int(10) unsigned DEFAULT NULL,
  `student_id` int(10) unsigned DEFAULT NULL,
  `record_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `dire_fees_installment_child_payments_bank_id_foreign` (`bank_id`),
  KEY `dire_fees_installment_child_payments_fees_type_id_foreign` (`fees_type_id`),
  KEY `dire_fees_installment_child_payments_student_id_foreign` (`student_id`),
  KEY `dire_fees_installment_child_payments_school_id_foreign` (`school_id`),
  CONSTRAINT `dire_fees_installment_child_payments_bank_id_foreign` FOREIGN KEY (`bank_id`) REFERENCES `sm_bank_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `dire_fees_installment_child_payments_fees_type_id_foreign` FOREIGN KEY (`fees_type_id`) REFERENCES `sm_fees_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `dire_fees_installment_child_payments_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `dire_fees_installment_child_payments_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `sm_students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `due_fees_login_prevents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned DEFAULT NULL,
  `role_id` int(10) unsigned DEFAULT NULL,
  `school_id` int(10) unsigned NOT NULL DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `due_fees_login_prevents_user_id_foreign` (`user_id`),
  KEY `due_fees_login_prevents_role_id_foreign` (`role_id`),
  KEY `due_fees_login_prevents_school_id_foreign` (`school_id`),
  KEY `due_fees_login_prevents_academic_id_foreign` (`academic_id`),
  CONSTRAINT `due_fees_login_prevents_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `due_fees_login_prevents_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `infix_roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `due_fees_login_prevents_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `due_fees_login_prevents_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fees_carry_forward_logs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `student_record_id` int(11) NOT NULL,
  `note` text NOT NULL,
  `amount` double(8,2) NOT NULL,
  `amount_type` varchar(191) NOT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `type` varchar(191) NOT NULL,
  `date` timestamp NOT NULL,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fees_carry_forward_logs_school_id_foreign` (`school_id`),
  CONSTRAINT `fees_carry_forward_logs_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fees_carry_forward_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(191) NOT NULL,
  `fees_due_days` int(11) NOT NULL,
  `payment_gateway` varchar(191) NOT NULL,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fees_carry_forward_settings_school_id_foreign` (`school_id`),
  CONSTRAINT `fees_carry_forward_settings_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fees_installment_credits` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(11) NOT NULL,
  `student_record_id` int(11) NOT NULL,
  `active_status` tinyint(1) NOT NULL DEFAULT 1,
  `school_id` int(11) NOT NULL,
  `amount` double(8,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fees_invoices` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `prefix` varchar(191) DEFAULT NULL,
  `start_form` int(11) DEFAULT NULL,
  `un_academic_id` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fees_invoices_school_id_foreign` (`school_id`),
  CONSTRAINT `fees_invoices_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fees_invoice_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `per_th` int(11) NOT NULL DEFAULT 2,
  `invoice_type` varchar(191) NOT NULL DEFAULT 'invoice',
  `student_name` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_section` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_class` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_roll` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_group` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_admission_no` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `footer_1` varchar(255) DEFAULT 'Parent/Student',
  `footer_2` varchar(255) NOT NULL DEFAULT 'Casier',
  `footer_3` varchar(255) NOT NULL DEFAULT 'Officer',
  `signature_p` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `signature_c` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `signature_o` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `c_signature_p` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `c_signature_c` tinyint(4) NOT NULL DEFAULT 0 COMMENT '0=No, 1=Yes',
  `c_signature_o` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `copy_s` varchar(255) DEFAULT 'Parent/Student',
  `copy_o` varchar(255) NOT NULL DEFAULT 'Office',
  `copy_c` varchar(255) NOT NULL DEFAULT 'Casier',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `copy_write_msg` text DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `fees_invoice_settings_created_by_foreign` (`created_by`),
  KEY `fees_invoice_settings_updated_by_foreign` (`updated_by`),
  KEY `fees_invoice_settings_school_id_foreign` (`school_id`),
  KEY `fees_invoice_settings_academic_id_foreign` (`academic_id`),
  CONSTRAINT `fees_invoice_settings_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fees_invoice_settings_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fees_invoice_settings_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fees_invoice_settings_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fm_fees_groups` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fm_fees_invoices` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `invoice_id` varchar(191) NOT NULL,
  `student_id` int(10) unsigned DEFAULT NULL,
  `class_id` int(11) DEFAULT NULL,
  `create_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `payment_status` varchar(191) DEFAULT NULL,
  `payment_method` varchar(191) DEFAULT NULL,
  `bank_id` int(11) DEFAULT NULL,
  `type` varchar(191) DEFAULT 'fees' COMMENT 'fees, lms',
  `school_id` int(11) DEFAULT NULL,
  `academic_id` int(11) DEFAULT NULL,
  `active_status` int(11) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `record_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fm_fees_invoices_student_id_foreign` (`student_id`),
  CONSTRAINT `fm_fees_invoices_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `sm_students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fm_fees_invoice_chields` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fees_invoice_id` bigint(20) unsigned DEFAULT NULL,
  `fees_type` int(11) DEFAULT NULL,
  `amount` double(8,2) DEFAULT NULL,
  `weaver` double(8,2) DEFAULT NULL,
  `fine` double(8,2) DEFAULT NULL,
  `sub_total` double(8,2) DEFAULT NULL,
  `paid_amount` double(8,2) DEFAULT NULL,
  `service_charge` double(8,2) DEFAULT NULL,
  `due_amount` double(8,2) DEFAULT NULL,
  `note` varchar(191) DEFAULT NULL,
  `school_id` int(11) DEFAULT NULL,
  `academic_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fm_fees_invoice_chields_fees_invoice_id_foreign` (`fees_invoice_id`),
  CONSTRAINT `fm_fees_invoice_chields_fees_invoice_id_foreign` FOREIGN KEY (`fees_invoice_id`) REFERENCES `fm_fees_invoices` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fm_fees_invoice_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `invoice_positions` text DEFAULT NULL,
  `uniq_id_start` varchar(191) DEFAULT NULL,
  `prefix` varchar(191) DEFAULT NULL,
  `class_limit` int(11) DEFAULT NULL,
  `section_limit` int(11) DEFAULT NULL,
  `admission_limit` int(11) DEFAULT NULL,
  `weaver` varchar(191) DEFAULT NULL,
  `school_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fm_fees_transactions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `invoice_number` varchar(191) DEFAULT NULL,
  `student_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `payment_method` varchar(191) DEFAULT NULL,
  `bank_id` int(11) DEFAULT NULL,
  `add_wallet_money` double(8,2) DEFAULT NULL,
  `payment_note` varchar(191) DEFAULT NULL,
  `file` text DEFAULT NULL,
  `paid_status` varchar(191) DEFAULT NULL,
  `fees_invoice_id` bigint(20) unsigned DEFAULT NULL,
  `school_id` int(11) DEFAULT NULL,
  `academic_id` int(11) DEFAULT NULL,
  `service_charge` double(8,2) DEFAULT NULL,
  `active_status` int(11) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `record_id` bigint(20) unsigned DEFAULT NULL,
  `total_paid_amount` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fm_fees_transactions_fees_invoice_id_foreign` (`fees_invoice_id`),
  CONSTRAINT `fm_fees_transactions_fees_invoice_id_foreign` FOREIGN KEY (`fees_invoice_id`) REFERENCES `fm_fees_invoices` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fm_fees_transaction_chields` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fees_type` varchar(191) DEFAULT NULL,
  `paid_amount` double(8,2) DEFAULT NULL,
  `service_charge` double(8,2) DEFAULT NULL,
  `fine` double(8,2) DEFAULT NULL,
  `weaver` double(8,2) DEFAULT NULL,
  `note` varchar(191) DEFAULT NULL,
  `fees_transaction_id` bigint(20) unsigned DEFAULT NULL,
  `school_id` int(11) DEFAULT NULL,
  `academic_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fm_fees_transaction_chields_fees_transaction_id_foreign` (`fees_transaction_id`),
  CONSTRAINT `fm_fees_transaction_chields_fees_transaction_id_foreign` FOREIGN KEY (`fees_transaction_id`) REFERENCES `fm_fees_transactions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fm_fees_types` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(230) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `fees_group_id` int(10) unsigned DEFAULT 1,
  `type` varchar(191) DEFAULT 'fees' COMMENT 'fees, lms',
  `course_id` int(11) DEFAULT NULL COMMENT 'Only For Lms',
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fm_fees_weavers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fees_invoice_id` bigint(20) unsigned DEFAULT NULL,
  `fees_type` int(11) DEFAULT NULL,
  `student_id` int(11) DEFAULT NULL,
  `weaver` double(8,2) DEFAULT NULL,
  `note` varchar(191) DEFAULT NULL,
  `school_id` int(11) DEFAULT NULL,
  `academic_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fm_fees_weavers_fees_invoice_id_foreign` (`fees_invoice_id`),
  CONSTRAINT `fm_fees_weavers_fees_invoice_id_foreign` FOREIGN KEY (`fees_invoice_id`) REFERENCES `fm_fees_invoices` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `invoice_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `per_th` int(11) NOT NULL DEFAULT 2,
  `prefix` varchar(191) DEFAULT NULL,
  `student_name` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_section` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_class` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_roll` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_group` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `student_admission_no` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `footer_1` varchar(255) DEFAULT 'Parent/Student',
  `footer_2` varchar(255) NOT NULL DEFAULT 'Casier',
  `footer_3` varchar(255) NOT NULL DEFAULT 'Officer',
  `signature_p` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `signature_c` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `signature_o` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `c_signature_p` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `c_signature_c` tinyint(4) NOT NULL DEFAULT 0 COMMENT '0=No, 1=Yes',
  `c_signature_o` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0=No, 1=Yes',
  `copy_s` varchar(255) DEFAULT 'Parent/Student',
  `copy_o` varchar(255) NOT NULL DEFAULT 'Office',
  `copy_c` varchar(255) NOT NULL DEFAULT 'Casier',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `copy_write_msg` text DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `invoice_settings_created_by_foreign` (`created_by`),
  KEY `invoice_settings_updated_by_foreign` (`updated_by`),
  KEY `invoice_settings_school_id_foreign` (`school_id`),
  KEY `invoice_settings_academic_id_foreign` (`academic_id`),
  CONSTRAINT `invoice_settings_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `invoice_settings_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `invoice_settings_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `invoice_settings_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payroll_payments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `sm_hr_payroll_generate_id` int(10) unsigned DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `payment_mode` varchar(191) DEFAULT NULL,
  `payment_method_id` int(10) unsigned DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `bank_id` int(11) DEFAULT NULL,
  `note` varchar(200) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `payroll_payments_sm_hr_payroll_generate_id_foreign` (`sm_hr_payroll_generate_id`),
  CONSTRAINT `payroll_payments_sm_hr_payroll_generate_id_foreign` FOREIGN KEY (`sm_hr_payroll_generate_id`) REFERENCES `sm_hr_payroll_generates` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_add_expenses` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `amount` double(10,2) DEFAULT NULL,
  `file` varchar(191) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `item_receive_id` int(11) DEFAULT NULL,
  `inventory_id` int(11) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `expense_head_id` int(10) unsigned DEFAULT NULL,
  `account_id` int(10) unsigned DEFAULT NULL,
  `payment_method_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `payroll_payment_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_add_expenses_school_id_foreign` (`school_id`),
  KEY `sm_add_expenses_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_add_expenses_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_add_expenses_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_add_incomes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `amount` double(10,2) DEFAULT NULL,
  `file` varchar(191) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `item_sell_id` int(11) DEFAULT NULL,
  `fees_collection_id` int(11) DEFAULT NULL,
  `inventory_id` int(11) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `income_head_id` int(10) unsigned DEFAULT NULL,
  `account_id` int(10) unsigned DEFAULT NULL,
  `payment_method_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT NULL,
  `installment_payment_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_add_incomes_account_id_foreign` (`account_id`),
  KEY `sm_add_incomes_payment_method_id_foreign` (`payment_method_id`),
  KEY `sm_add_incomes_school_id_foreign` (`school_id`),
  KEY `sm_add_incomes_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_add_incomes_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_add_incomes_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `sm_bank_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_add_incomes_payment_method_id_foreign` FOREIGN KEY (`payment_method_id`) REFERENCES `sm_payment_methhods` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_add_incomes_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_bank_accounts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `bank_name` varchar(191) DEFAULT NULL,
  `account_name` varchar(191) DEFAULT NULL,
  `account_number` varchar(191) DEFAULT NULL,
  `account_type` varchar(191) DEFAULT NULL,
  `opening_balance` double NOT NULL DEFAULT 0,
  `current_balance` double NOT NULL DEFAULT 0,
  `note` text DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_bank_accounts_school_id_foreign` (`school_id`),
  KEY `sm_bank_accounts_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_bank_accounts_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_bank_accounts_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_bank_payment_slips` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `amount` double(10,2) DEFAULT NULL,
  `slip` varchar(191) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `bank_id` int(11) DEFAULT NULL,
  `approve_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '0 pending, 1 approve',
  `payment_mode` varchar(191) NOT NULL COMMENT 'Bk= bank, Cq=Cheque',
  `reason` text DEFAULT NULL,
  `fees_discount_id` int(10) unsigned DEFAULT NULL,
  `fees_type_id` int(10) unsigned DEFAULT NULL,
  `record_id` int(10) unsigned DEFAULT NULL,
  `student_id` int(10) unsigned DEFAULT NULL,
  `class_id` int(10) unsigned DEFAULT NULL,
  `assign_id` int(10) unsigned DEFAULT NULL,
  `section_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `child_payment_id` int(11) DEFAULT NULL,
  `installment_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `active_status` int(11) DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_bank_payment_slips_fees_discount_id_foreign` (`fees_discount_id`),
  KEY `sm_bank_payment_slips_student_id_foreign` (`student_id`),
  KEY `sm_bank_payment_slips_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_bank_payment_slips_fees_discount_id_foreign` FOREIGN KEY (`fees_discount_id`) REFERENCES `sm_fees_discounts` (`id`),
  CONSTRAINT `sm_bank_payment_slips_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`),
  CONSTRAINT `sm_bank_payment_slips_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `sm_students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_bank_statements` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `bank_id` int(11) DEFAULT NULL,
  `after_balance` int(11) DEFAULT NULL,
  `amount` double(10,2) DEFAULT NULL,
  `type` varchar(11) DEFAULT NULL COMMENT '1 for Income 0 for Expense',
  `payment_method` int(10) unsigned DEFAULT NULL,
  `details` varchar(500) DEFAULT NULL,
  `item_receive_id` int(11) DEFAULT NULL,
  `item_receive_bank_statement_id` int(11) DEFAULT NULL,
  `item_sell_bank_statement_id` int(11) DEFAULT NULL,
  `item_sell_id` int(11) DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT NULL,
  `fees_payment_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `payroll_payment_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_donors` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `full_name` varchar(200) DEFAULT NULL,
  `profession` varchar(200) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `mobile` varchar(200) DEFAULT NULL,
  `photo` varchar(191) DEFAULT NULL,
  `age` varchar(200) DEFAULT NULL,
  `current_address` varchar(500) DEFAULT NULL,
  `permanent_address` varchar(500) DEFAULT NULL,
  `show_public` tinyint(4) NOT NULL DEFAULT 1,
  `custom_field` text DEFAULT NULL,
  `custom_field_form_name` varchar(191) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `bloodgroup_id` int(10) unsigned DEFAULT NULL,
  `religion_id` int(10) unsigned DEFAULT NULL,
  `gender_id` int(10) unsigned DEFAULT NULL,
  `school_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_donors_bloodgroup_id_foreign` (`bloodgroup_id`),
  KEY `sm_donors_religion_id_foreign` (`religion_id`),
  KEY `sm_donors_gender_id_foreign` (`gender_id`),
  KEY `sm_donors_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_donors_bloodgroup_id_foreign` FOREIGN KEY (`bloodgroup_id`) REFERENCES `sm_base_setups` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sm_donors_gender_id_foreign` FOREIGN KEY (`gender_id`) REFERENCES `sm_base_setups` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sm_donors_religion_id_foreign` FOREIGN KEY (`religion_id`) REFERENCES `sm_base_setups` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sm_donors_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_expense_heads` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_expense_heads_school_id_foreign` (`school_id`),
  KEY `sm_expense_heads_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_expense_heads_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_expense_heads_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_fees_assigns` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `fees_amount` double(10,2) DEFAULT NULL,
  `applied_discount` double(10,2) DEFAULT NULL,
  `fees_master_id` int(10) unsigned DEFAULT NULL,
  `fees_discount_id` int(10) unsigned DEFAULT NULL,
  `record_id` int(10) unsigned DEFAULT NULL,
  `student_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `class_id` int(10) unsigned DEFAULT NULL,
  `section_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_fees_assigns_fees_master_id_foreign` (`fees_master_id`),
  KEY `sm_fees_assigns_fees_discount_id_foreign` (`fees_discount_id`),
  KEY `sm_fees_assigns_student_id_foreign` (`student_id`),
  KEY `sm_fees_assigns_school_id_foreign` (`school_id`),
  KEY `sm_fees_assigns_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_fees_assigns_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_assigns_fees_discount_id_foreign` FOREIGN KEY (`fees_discount_id`) REFERENCES `sm_fees_discounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_assigns_fees_master_id_foreign` FOREIGN KEY (`fees_master_id`) REFERENCES `sm_fees_masters` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_assigns_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_assigns_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `sm_students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_fees_assign_discounts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `student_id` int(10) unsigned DEFAULT NULL,
  `record_id` int(10) unsigned DEFAULT NULL,
  `fees_discount_id` int(10) unsigned DEFAULT NULL,
  `fees_type_id` int(10) unsigned DEFAULT NULL,
  `fees_group_id` int(10) unsigned DEFAULT NULL,
  `applied_amount` double DEFAULT 0,
  `unapplied_amount` double DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_fees_assign_discounts_student_id_foreign` (`student_id`),
  KEY `sm_fees_assign_discounts_fees_discount_id_foreign` (`fees_discount_id`),
  KEY `sm_fees_assign_discounts_school_id_foreign` (`school_id`),
  KEY `sm_fees_assign_discounts_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_fees_assign_discounts_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_assign_discounts_fees_discount_id_foreign` FOREIGN KEY (`fees_discount_id`) REFERENCES `sm_fees_discounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_assign_discounts_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_assign_discounts_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `sm_students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_fees_carry_forwards` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `balance` double(16,2) NOT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `notes` varchar(191) NOT NULL DEFAULT 'Fees Carry Forward',
  `balance_type` varchar(191) DEFAULT NULL,
  `due_date` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `student_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_fees_carry_forwards_student_id_foreign` (`student_id`),
  KEY `sm_fees_carry_forwards_school_id_foreign` (`school_id`),
  KEY `sm_fees_carry_forwards_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_fees_carry_forwards_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_carry_forwards_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_carry_forwards_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `sm_students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_fees_discounts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) DEFAULT NULL,
  `code` varchar(200) DEFAULT NULL,
  `type` enum('once','year') DEFAULT NULL COMMENT 'once for one time, year for all months',
  `amount` double(10,2) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `record_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_fees_discounts_school_id_foreign` (`school_id`),
  KEY `sm_fees_discounts_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_fees_discounts_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_discounts_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_fees_groups` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) DEFAULT NULL,
  `type` varchar(200) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `description` text DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `un_semester_label_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_fees_groups_school_id_foreign` (`school_id`),
  KEY `sm_fees_groups_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_fees_groups_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_groups_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_fees_masters` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `amount` double(10,2) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `fees_group_id` int(10) unsigned DEFAULT NULL,
  `fees_type_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `class_id` int(10) unsigned DEFAULT NULL,
  `section_id` int(10) unsigned DEFAULT NULL,
  `un_semester_label_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_fees_masters_fees_group_id_foreign` (`fees_group_id`),
  KEY `sm_fees_masters_fees_type_id_foreign` (`fees_type_id`),
  KEY `sm_fees_masters_school_id_foreign` (`school_id`),
  KEY `sm_fees_masters_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_fees_masters_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_masters_fees_group_id_foreign` FOREIGN KEY (`fees_group_id`) REFERENCES `sm_fees_groups` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_masters_fees_type_id_foreign` FOREIGN KEY (`fees_type_id`) REFERENCES `sm_fees_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_masters_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_fees_payments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `discount_month` tinyint(4) DEFAULT NULL,
  `discount_amount` double(8,2) DEFAULT NULL,
  `fine` double(8,2) DEFAULT NULL,
  `amount` double(10,2) DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `payment_mode` varchar(100) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `slip` varchar(191) DEFAULT NULL,
  `fine_title` varchar(191) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `assign_id` int(10) unsigned DEFAULT NULL,
  `bank_id` int(10) unsigned DEFAULT NULL,
  `fees_discount_id` int(10) unsigned DEFAULT NULL,
  `fees_type_id` int(10) unsigned DEFAULT NULL,
  `record_id` int(10) unsigned DEFAULT NULL,
  `student_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `direct_fees_installment_assign_id` int(10) unsigned DEFAULT NULL,
  `installment_payment_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_fees_payments_assign_id_foreign` (`assign_id`),
  KEY `sm_fees_payments_bank_id_foreign` (`bank_id`),
  KEY `sm_fees_payments_fees_discount_id_foreign` (`fees_discount_id`),
  KEY `sm_fees_payments_fees_type_id_foreign` (`fees_type_id`),
  KEY `sm_fees_payments_student_id_foreign` (`student_id`),
  KEY `sm_fees_payments_school_id_foreign` (`school_id`),
  KEY `sm_fees_payments_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_fees_payments_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_payments_assign_id_foreign` FOREIGN KEY (`assign_id`) REFERENCES `sm_fees_assigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_payments_bank_id_foreign` FOREIGN KEY (`bank_id`) REFERENCES `sm_bank_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_payments_fees_discount_id_foreign` FOREIGN KEY (`fees_discount_id`) REFERENCES `sm_fees_discounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_payments_fees_type_id_foreign` FOREIGN KEY (`fees_type_id`) REFERENCES `sm_fees_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_payments_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_payments_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `sm_students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_fees_types` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(230) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `fees_group_id` int(10) unsigned DEFAULT 1,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  `un_semester_label_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_fees_types_fees_group_id_foreign` (`fees_group_id`),
  KEY `sm_fees_types_school_id_foreign` (`school_id`),
  KEY `sm_fees_types_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_fees_types_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_types_fees_group_id_foreign` FOREIGN KEY (`fees_group_id`) REFERENCES `sm_fees_groups` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_fees_types_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_hr_payroll_earn_deducs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type_name` varchar(191) DEFAULT NULL,
  `amount` double(10,2) DEFAULT NULL,
  `earn_dedc_type` varchar(5) DEFAULT NULL COMMENT 'e for earnings and d for deductions',
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `payroll_generate_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_hr_payroll_earn_deducs_payroll_generate_id_foreign` (`payroll_generate_id`),
  KEY `sm_hr_payroll_earn_deducs_school_id_foreign` (`school_id`),
  KEY `sm_hr_payroll_earn_deducs_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_hr_payroll_earn_deducs_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_hr_payroll_earn_deducs_payroll_generate_id_foreign` FOREIGN KEY (`payroll_generate_id`) REFERENCES `sm_hr_payroll_generates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_hr_payroll_earn_deducs_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_hr_payroll_generates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `basic_salary` double DEFAULT NULL,
  `total_earning` double DEFAULT NULL,
  `total_deduction` double DEFAULT NULL,
  `gross_salary` double DEFAULT NULL,
  `tax` double DEFAULT NULL,
  `net_salary` double DEFAULT NULL,
  `payroll_month` varchar(191) DEFAULT NULL,
  `payroll_year` varchar(191) DEFAULT NULL,
  `payroll_status` varchar(191) DEFAULT NULL COMMENT 'NG for not generated, G for generated, P for paid',
  `payment_mode` varchar(191) DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `bank_id` int(11) DEFAULT NULL,
  `note` varchar(200) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `paid_amount` int(11) DEFAULT NULL,
  `is_partial` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `staff_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_hr_payroll_generates_staff_id_foreign` (`staff_id`),
  KEY `sm_hr_payroll_generates_school_id_foreign` (`school_id`),
  KEY `sm_hr_payroll_generates_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_hr_payroll_generates_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_hr_payroll_generates_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_hr_payroll_generates_staff_id_foreign` FOREIGN KEY (`staff_id`) REFERENCES `sm_staffs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_income_heads` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_income_heads_school_id_foreign` (`school_id`),
  KEY `sm_income_heads_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_income_heads_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_income_heads_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_inventory_payments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `item_receive_sell_id` int(10) unsigned DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `amount` double(10,2) DEFAULT NULL,
  `reference_no` varchar(50) DEFAULT NULL,
  `payment_type` varchar(11) DEFAULT NULL COMMENT 'R for receive S for sell',
  `payment_method` int(10) unsigned DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_inventory_payments_school_id_foreign` (`school_id`),
  KEY `sm_inventory_payments_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_inventory_payments_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_inventory_payments_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_payment_gateway_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `gateway_name` varchar(191) DEFAULT NULL,
  `gateway_username` varchar(191) DEFAULT NULL,
  `gateway_password` varchar(191) DEFAULT NULL,
  `gateway_signature` varchar(191) DEFAULT NULL,
  `gateway_client_id` varchar(191) DEFAULT NULL,
  `gateway_mode` varchar(191) DEFAULT NULL,
  `gateway_secret_key` varchar(191) DEFAULT NULL,
  `gateway_secret_word` varchar(191) DEFAULT NULL,
  `gateway_publisher_key` varchar(191) DEFAULT NULL,
  `gateway_private_key` varchar(191) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `bank_details` text DEFAULT NULL,
  `cheque_details` text DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `service_charge` tinyint(1) DEFAULT 0,
  `charge_type` varchar(2) DEFAULT NULL COMMENT 'P=percentage, F=Flat',
  `charge` double(8,2) DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `sm_payment_gateway_settings_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_payment_gateway_settings_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_payment_methhods` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `method` varchar(255) NOT NULL,
  `type` varchar(191) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `gateway_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_payment_methhods_gateway_id_foreign` (`gateway_id`),
  KEY `sm_payment_methhods_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_payment_methhods_gateway_id_foreign` FOREIGN KEY (`gateway_id`) REFERENCES `sm_payment_gateway_settings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_payment_methhods_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_product_purchases` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `purchase_date` date NOT NULL,
  `expaire_date` date NOT NULL,
  `price` double(10,2) DEFAULT NULL,
  `paid_amount` double(10,2) DEFAULT NULL,
  `due_amount` double(10,2) DEFAULT NULL,
  `package` varchar(10) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `staff_id` int(10) unsigned DEFAULT NULL,
  `school_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_product_purchases_user_id_foreign` (`user_id`),
  KEY `sm_product_purchases_staff_id_foreign` (`staff_id`),
  KEY `sm_product_purchases_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_product_purchases_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_product_purchases_staff_id_foreign` FOREIGN KEY (`staff_id`) REFERENCES `sm_staffs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_product_purchases_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_question_banks` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(2) NOT NULL COMMENT 'M for multi ans, T for trueFalse, F for fill in the blanks',
  `question` text DEFAULT NULL,
  `marks` int(11) DEFAULT NULL,
  `trueFalse` varchar(1) DEFAULT NULL COMMENT 'F = false, T = true ',
  `suitable_words` text DEFAULT NULL,
  `number_of_option` varchar(2) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `q_group_id` int(10) unsigned DEFAULT NULL,
  `class_id` int(10) unsigned DEFAULT NULL,
  `section_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_question_banks_q_group_id_foreign` (`q_group_id`),
  KEY `sm_question_banks_class_id_foreign` (`class_id`),
  KEY `sm_question_banks_section_id_foreign` (`section_id`),
  KEY `sm_question_banks_school_id_foreign` (`school_id`),
  KEY `sm_question_banks_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_question_banks_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_question_banks_class_id_foreign` FOREIGN KEY (`class_id`) REFERENCES `sm_classes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_question_banks_q_group_id_foreign` FOREIGN KEY (`q_group_id`) REFERENCES `sm_question_groups` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_question_banks_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_question_banks_section_id_foreign` FOREIGN KEY (`section_id`) REFERENCES `sm_sections` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_question_bank_mu_options` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(191) DEFAULT NULL,
  `status` tinyint(4) DEFAULT NULL COMMENT '0 = false, 1 = correct',
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `question_bank_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_question_bank_mu_options_question_bank_id_foreign` (`question_bank_id`),
  KEY `sm_question_bank_mu_options_school_id_foreign` (`school_id`),
  KEY `sm_question_bank_mu_options_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_question_bank_mu_options_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_question_bank_mu_options_question_bank_id_foreign` FOREIGN KEY (`question_bank_id`) REFERENCES `sm_question_banks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_question_bank_mu_options_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `transcations` (
  `id` int(11) NOT NULL,
  `title` text DEFAULT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'debit',
  `payment_method` varchar(20) DEFAULT NULL,
  `reference` varchar(20) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `morphable_id` bigint(20) unsigned DEFAULT NULL,
  `morphable_type` varchar(191) DEFAULT NULL,
  `amount` bigint(20) NOT NULL DEFAULT 0,
  `transaction_date` date DEFAULT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `school_id` int(11) NOT NULL DEFAULT 1,
  `academic_id` int(11) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  KEY `transcations_user_id_foreign` (`user_id`),
  CONSTRAINT `transcations_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wallet_transactions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `amount` double(8,2) DEFAULT NULL,
  `payment_method` varchar(191) DEFAULT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `bank_id` int(11) DEFAULT NULL,
  `note` varchar(191) DEFAULT NULL,
  `type` varchar(191) DEFAULT NULL COMMENT 'diposit, refund, expense, fees_refund',
  `file` text DEFAULT NULL,
  `reject_note` text DEFAULT NULL,
  `expense` double(8,2) DEFAULT NULL,
  `status` varchar(191) NOT NULL DEFAULT 'pending' COMMENT 'pending, approve, reject',
  `created_by` int(11) DEFAULT NULL,
  `academic_id` int(11) NOT NULL DEFAULT 1,
  `school_id` int(11) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `wallet_transactions_user_id_foreign` (`user_id`),
  CONSTRAINT `wallet_transactions_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


SET FOREIGN_KEY_CHECKS=1;
