SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS `behaviour_record_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `student_comment` int(11) DEFAULT NULL,
  `parent_comment` int(11) DEFAULT NULL,
  `student_view` int(11) DEFAULT NULL,
  `parent_view` int(11) DEFAULT NULL,
  `school_id` int(10) unsigned NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `colors` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) DEFAULT NULL,
  `is_color` tinyint(1) DEFAULT 1,
  `status` tinyint(1) DEFAULT 1,
  `default_value` varchar(191) DEFAULT NULL,
  `lawn_green` varchar(191) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `color_theme` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `color_id` bigint(20) unsigned DEFAULT NULL,
  `value` varchar(191) DEFAULT NULL,
  `theme_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `color_theme_color_id_foreign` (`color_id`),
  KEY `color_theme_theme_id_foreign` (`theme_id`),
  CONSTRAINT `color_theme_color_id_foreign` FOREIGN KEY (`color_id`) REFERENCES `colors` (`id`) ON DELETE CASCADE,
  CONSTRAINT `color_theme_theme_id_foreign` FOREIGN KEY (`theme_id`) REFERENCES `themes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_background_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `is_default` int(11) NOT NULL DEFAULT 0,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_background_settings_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_background_settings_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_base_setups` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `base_setup_name` varchar(255) NOT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `base_group_id` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_base_setups_base_group_id_foreign` (`base_group_id`),
  KEY `sm_base_setups_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_base_setups_base_group_id_foreign` FOREIGN KEY (`base_group_id`) REFERENCES `sm_base_groups` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_base_setups_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_custom_links` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title1` varchar(255) DEFAULT NULL,
  `title2` varchar(255) DEFAULT NULL,
  `title3` varchar(255) DEFAULT NULL,
  `title4` varchar(255) DEFAULT NULL,
  `link_label1` varchar(255) DEFAULT NULL,
  `link_href1` varchar(255) DEFAULT NULL,
  `link_label2` varchar(255) DEFAULT NULL,
  `link_href2` varchar(255) DEFAULT NULL,
  `link_label3` varchar(255) DEFAULT NULL,
  `link_href3` varchar(255) DEFAULT NULL,
  `link_label4` varchar(255) DEFAULT NULL,
  `link_href4` varchar(255) DEFAULT NULL,
  `link_label5` varchar(255) DEFAULT NULL,
  `link_href5` varchar(255) DEFAULT NULL,
  `link_label6` varchar(255) DEFAULT NULL,
  `link_href6` varchar(255) DEFAULT NULL,
  `link_label7` varchar(255) DEFAULT NULL,
  `link_href7` varchar(255) DEFAULT NULL,
  `link_label8` varchar(255) DEFAULT NULL,
  `link_href8` varchar(255) DEFAULT NULL,
  `link_label9` varchar(255) DEFAULT NULL,
  `link_href9` varchar(255) DEFAULT NULL,
  `link_label10` varchar(255) DEFAULT NULL,
  `link_href10` varchar(255) DEFAULT NULL,
  `link_label11` varchar(255) DEFAULT NULL,
  `link_href11` varchar(255) DEFAULT NULL,
  `link_label12` varchar(255) DEFAULT NULL,
  `link_href12` varchar(255) DEFAULT NULL,
  `link_label13` varchar(255) DEFAULT NULL,
  `link_href13` varchar(255) DEFAULT NULL,
  `link_label14` varchar(255) DEFAULT NULL,
  `link_href14` varchar(255) DEFAULT NULL,
  `link_label15` varchar(255) DEFAULT NULL,
  `link_href15` varchar(255) DEFAULT NULL,
  `link_label16` varchar(255) DEFAULT NULL,
  `link_href16` varchar(255) DEFAULT NULL,
  `facebook_url` varchar(255) DEFAULT NULL,
  `twitter_url` varchar(255) DEFAULT NULL,
  `dribble_url` varchar(255) DEFAULT NULL,
  `linkedin_url` varchar(255) DEFAULT NULL,
  `behance_url` varchar(255) DEFAULT NULL,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_custom_links_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_custom_links_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_dashboard_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dashboard_sec_id` int(11) NOT NULL,
  `active_status` int(11) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `role_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_dashboard_settings_role_id_foreign` (`role_id`),
  KEY `sm_dashboard_settings_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_dashboard_settings_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_dashboard_settings_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_date_formats` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `format` varchar(191) DEFAULT NULL,
  `normal_view` varchar(191) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_date_formats_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_date_formats_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_general_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `school_name` varchar(191) DEFAULT NULL,
  `site_title` varchar(191) DEFAULT NULL,
  `school_code` varchar(191) DEFAULT NULL,
  `address` varchar(191) DEFAULT NULL,
  `phone` varchar(191) DEFAULT NULL,
  `email` varchar(191) DEFAULT NULL,
  `file_size` varchar(191) NOT NULL DEFAULT '102400',
  `currency` varchar(191) DEFAULT 'USD',
  `currency_symbol` varchar(191) DEFAULT '$',
  `currency_format` varchar(191) DEFAULT 'symbol_amount',
  `promotionSetting` int(11) DEFAULT 0,
  `logo` varchar(191) DEFAULT NULL,
  `favicon` varchar(191) DEFAULT NULL,
  `system_version` varchar(191) DEFAULT '8.2.3',
  `active_status` int(11) DEFAULT 1,
  `currency_code` varchar(191) DEFAULT 'USD',
  `language_name` varchar(191) DEFAULT 'en',
  `session_year` varchar(191) DEFAULT '2020',
  `system_purchase_code` text DEFAULT NULL,
  `system_activated_date` date DEFAULT NULL,
  `last_update` date DEFAULT NULL,
  `envato_user` varchar(191) DEFAULT NULL,
  `envato_item_id` varchar(191) DEFAULT NULL,
  `system_domain` varchar(191) DEFAULT NULL,
  `copyright_text` text DEFAULT NULL,
  `api_url` int(11) NOT NULL DEFAULT 1,
  `website_btn` int(11) NOT NULL DEFAULT 1,
  `dashboard_btn` int(11) NOT NULL DEFAULT 1,
  `report_btn` int(11) NOT NULL DEFAULT 1,
  `style_btn` int(11) NOT NULL DEFAULT 1,
  `ltl_rtl_btn` int(11) NOT NULL DEFAULT 1,
  `lang_btn` int(11) NOT NULL DEFAULT 1,
  `website_url` varchar(191) DEFAULT NULL,
  `ttl_rtl` int(11) NOT NULL DEFAULT 2,
  `phone_number_privacy` int(11) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `week_start_id` int(11) DEFAULT NULL,
  `time_zone_id` int(11) DEFAULT NULL,
  `attendance_layout` int(11) DEFAULT 1,
  `session_id` int(10) unsigned DEFAULT NULL,
  `language_id` int(10) unsigned DEFAULT 1,
  `date_format_id` int(10) unsigned DEFAULT 1,
  `ss_page_load` int(11) DEFAULT 3,
  `sub_topic_enable` tinyint(1) NOT NULL DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `software_version` varchar(100) DEFAULT NULL,
  `email_driver` varchar(191) NOT NULL DEFAULT 'php',
  `fcm_key` text DEFAULT NULL,
  `multiple_roll` tinyint(4) DEFAULT 0,
  `Lesson` int(11) DEFAULT 1,
  `Chat` int(11) DEFAULT 1,
  `FeesCollection` int(11) DEFAULT 0,
  `income_head_id` int(11) DEFAULT 0,
  `InfixBiometrics` int(11) DEFAULT 0,
  `ResultReports` int(11) DEFAULT 0,
  `TemplateSettings` int(11) DEFAULT 1,
  `MenuManage` int(11) DEFAULT 1,
  `RolePermission` int(11) DEFAULT 1,
  `RazorPay` int(11) DEFAULT 0,
  `Saas` int(11) DEFAULT 1,
  `StudentAbsentNotification` int(11) DEFAULT 1,
  `ParentRegistration` int(11) DEFAULT 0,
  `Zoom` int(11) DEFAULT 0,
  `BBB` int(11) DEFAULT 0,
  `VideoWatch` int(11) DEFAULT 0,
  `Jitsi` int(11) DEFAULT 0,
  `OnlineExam` int(11) DEFAULT 0,
  `SaasRolePermission` int(11) DEFAULT 0,
  `BulkPrint` int(11) DEFAULT 1,
  `HimalayaSms` int(11) DEFAULT 1,
  `XenditPayment` int(11) DEFAULT 1,
  `Wallet` int(11) DEFAULT 1,
  `Lms` int(11) DEFAULT 0,
  `ExamPlan` int(11) DEFAULT 1,
  `University` int(11) DEFAULT 0,
  `Gmeet` int(11) DEFAULT 0,
  `KhaltiPayment` int(11) DEFAULT 0,
  `Raudhahpay` int(11) DEFAULT 0,
  `AppSlider` int(11) DEFAULT 1,
  `BehaviourRecords` int(11) DEFAULT 0,
  `DownloadCenter` int(11) DEFAULT 1,
  `AiContent` int(11) DEFAULT 0,
  `WhatsappSupport` int(11) DEFAULT 0,
  `InAppLiveClass` int(11) DEFAULT 0,
  `fees_status` int(11) DEFAULT 1,
  `lms_checkout` int(11) DEFAULT 0,
  `academic_id` int(10) unsigned DEFAULT NULL,
  `is_comment` tinyint(4) DEFAULT 0,
  `auto_approve` tinyint(4) DEFAULT 0,
  `blog_search` tinyint(4) DEFAULT 1,
  `recent_blog` tinyint(4) DEFAULT 1,
  `un_academic_id` int(10) unsigned DEFAULT 1,
  `direct_fees_assign` tinyint(1) NOT NULL DEFAULT 0,
  `with_guardian` tinyint(1) NOT NULL DEFAULT 1,
  `result_type` varchar(191) DEFAULT NULL,
  `preloader_status` tinyint(1) NOT NULL DEFAULT 1,
  `preloader_style` tinyint(4) NOT NULL DEFAULT 3,
  `preloader_type` tinyint(4) NOT NULL DEFAULT 1,
  `preloader_image` varchar(191) NOT NULL DEFAULT 'public/uploads/settings/preloader/preloader1.gif',
  `due_fees_login` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 = Login restricted by due date , 0 = No Restriction ',
  `two_factor` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 = Enable , 0 = Disable',
  `active_theme` varchar(191) NOT NULL DEFAULT 'edulia',
  `queue_connection` varchar(191) NOT NULL DEFAULT 'database',
  `is_custom_saas` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `sm_general_settings_session_id_foreign` (`session_id`),
  KEY `sm_general_settings_language_id_foreign` (`language_id`),
  KEY `sm_general_settings_date_format_id_foreign` (`date_format_id`),
  KEY `sm_general_settings_school_id_foreign` (`school_id`),
  KEY `sm_general_settings_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_general_settings_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sm_general_settings_date_format_id_foreign` FOREIGN KEY (`date_format_id`) REFERENCES `sm_date_formats` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sm_general_settings_language_id_foreign` FOREIGN KEY (`language_id`) REFERENCES `sm_languages` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sm_general_settings_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_general_settings_session_id_foreign` FOREIGN KEY (`session_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_languages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `language_name` varchar(191) DEFAULT NULL,
  `native` varchar(191) DEFAULT NULL,
  `language_universal` varchar(191) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `lang_id` int(10) unsigned DEFAULT 1,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_languages_lang_id_foreign` (`lang_id`),
  KEY `sm_languages_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_languages_lang_id_foreign` FOREIGN KEY (`lang_id`) REFERENCES `languages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_languages_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_language_phrases` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `modules` text DEFAULT NULL,
  `default_phrases` text DEFAULT NULL,
  `en` text DEFAULT NULL,
  `es` text DEFAULT NULL,
  `bn` text DEFAULT NULL,
  `fr` text DEFAULT NULL,
  `school_id` int(10) unsigned DEFAULT 1,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sm_language_phrases_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_language_phrases_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `sm_setup_admins` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` tinyint(4) DEFAULT NULL COMMENT '1 purpose, 2 complaint type, 3 source, 4 Reference',
  `name` varchar(191) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  `academic_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_setup_admins_school_id_foreign` (`school_id`),
  KEY `sm_setup_admins_academic_id_foreign` (`academic_id`),
  CONSTRAINT `sm_setup_admins_academic_id_foreign` FOREIGN KEY (`academic_id`) REFERENCES `sm_academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sm_setup_admins_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sm_styles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `style_name` varchar(255) DEFAULT NULL,
  `path_main_style` varchar(255) DEFAULT NULL,
  `path_infix_style` varchar(255) DEFAULT NULL,
  `primary_color` varchar(255) DEFAULT NULL,
  `primary_color2` varchar(255) DEFAULT NULL,
  `title_color` varchar(255) DEFAULT NULL,
  `text_color` varchar(255) DEFAULT NULL,
  `white` varchar(255) DEFAULT NULL,
  `black` varchar(255) DEFAULT NULL,
  `sidebar_bg` varchar(255) DEFAULT NULL,
  `barchart1` varchar(255) DEFAULT NULL,
  `barchart2` varchar(255) DEFAULT NULL,
  `barcharttextcolor` varchar(255) DEFAULT NULL,
  `barcharttextfamily` varchar(255) DEFAULT NULL,
  `areachartlinecolor1` varchar(255) DEFAULT NULL,
  `areachartlinecolor2` varchar(255) DEFAULT NULL,
  `dashboardbackground` varchar(255) DEFAULT NULL,
  `active_status` tinyint(4) NOT NULL DEFAULT 1,
  `is_active` tinyint(4) NOT NULL DEFAULT 0,
  `is_default` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'if 1 then yes, if 0 then no',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT 1,
  `updated_by` int(10) unsigned DEFAULT 1,
  `school_id` int(10) unsigned DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `sm_styles_school_id_foreign` (`school_id`),
  CONSTRAINT `sm_styles_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `themes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(191) DEFAULT NULL,
  `path_main_style` varchar(255) DEFAULT NULL,
  `path_infix_style` varchar(255) DEFAULT NULL,
  `replicate_theme` varchar(255) DEFAULT NULL,
  `color_mode` varchar(191) NOT NULL DEFAULT 'gradient',
  `box_shadow` tinyint(1) DEFAULT 1,
  `background_type` varchar(191) NOT NULL DEFAULT 'image',
  `background_color` varchar(191) DEFAULT NULL,
  `background_image` varchar(191) DEFAULT NULL,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `is_system` tinyint(1) NOT NULL DEFAULT 0,
  `created_by` int(11) DEFAULT NULL,
  `school_id` int(10) unsigned DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `themes_school_id_foreign` (`school_id`),
  CONSTRAINT `themes_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `sm_schools` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


SET FOREIGN_KEY_CHECKS=1;
