//! # Academic-domain repository port traits
//!
//! The repository port traits for academic aggregates were originally
//! defined in this module (StudentRepository, ClassRepository, etc.)
//! but were never implemented by any storage adapter. They have been
//! removed as unused dead code (Wave 228).
//!
//! When the engine needs per-aggregate repository abstractions, this
//! module will be regenerated by `tools/dispatcher-gen/gen_aggregate.py`
//! alongside the corresponding storage adapter implementation.
