//! CMS-domain child entities.
//!
//! Per `docs/specs/cms/entities.md`. Entities have identity and
//! lifecycle but are not aggregate roots. They are loaded and
//! persisted only through their aggregate root.
//!
//! The CMS domain ships 6 child entities:
//! - `NewsImage` (owned by `News`)
//! - `ContentShareListAudience` (owned by `ContentShareList`)
//! - `ContentShareListContent` (owned by `ContentShareList`)
//! - `PageRevision` (owned by `Page`)
//! - `NewsRevision` (owned by `News`)
//! - `ContentRevision` (owned by `Content`)
//!
//! Per the spec, several value-object children (`PageSettings`,
//! `ContentAvailability`, `TeacherUploadContentScope`,
//! `UploadContentScope`, `HomeSliderOrder`, `TestimonialImage`)
//! are embedded in the parent aggregate and are not separate
//! entities; the typed wrappers live in the aggregate file.

#![allow(dead_code, clippy::all)]
#![allow(missing_docs)]

use chrono::{DateTime, Utc};
use educore_core::ids::{SchoolId, UserId};
use serde::{Deserialize, Serialize};

use crate::value_objects::{
    ContentId, ContentRevisionId, ContentShareListAudienceId, ContentShareListContentId,
    ContentShareListId, FileReference, NewsId, NewsImageId, NewsRevisionId, PageId, PageRevisionId,
};

// =============================================================================
// NewsImage (owned by News)
// =============================================================================

/// A news-image child entity. The `image` and `image_thumb`
/// references for a [`News`](crate::aggregate::News) entry. Both
/// are [`FileReference`]s; the thumb is generated by an image
/// processing port (deferred to Phase 15). The child entity has
/// its own typed id (`NewsImageId`) but is loaded and persisted
/// only through its aggregate root.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NewsImage {
    /// The typed id.
    pub id: NewsImageId,
    /// The owning news id (FK to the parent aggregate).
    pub news_id: NewsId,
    /// The owning school.
    pub school_id: SchoolId,
    /// The image file.
    pub image: FileReference,
    /// The optional thumbnail file.
    pub image_thumb: Option<FileReference>,
    /// The creation timestamp.
    pub created_at: DateTime<Utc>,
    /// The last-update timestamp.
    pub updated_at: DateTime<Utc>,
    /// The creating user.
    pub created_by: UserId,
    /// The last-updating user.
    pub updated_by: UserId,
}

// =============================================================================
// PageRevision (owned by Page)
// =============================================================================

/// A historical snapshot of a [`Page`](crate::aggregate::Page)
/// body. Revisions are append-only and allow reverting the page
/// to a prior state. The child entity has its own typed id
/// (`PageRevisionId`) but is loaded and persisted only through
/// its aggregate root.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PageRevision {
    /// The typed id.
    pub id: PageRevisionId,
    /// The owning page id (FK to the parent aggregate).
    pub page_id: PageId,
    /// The owning school.
    pub school_id: SchoolId,
    /// The revision body (the page's body at the time of the
    /// snapshot).
    pub body: String,
    /// The revision number (monotonically increasing per page).
    pub revision_number: u32,
    /// The creation timestamp.
    pub created_at: DateTime<Utc>,
    /// The user who created the revision.
    pub created_by: UserId,
}

// =============================================================================
// NewsRevision (owned by News)
// =============================================================================

/// A historical snapshot of a [`News`](crate::aggregate::News)
/// body. Revisions are append-only.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NewsRevision {
    /// The typed id.
    pub id: NewsRevisionId,
    /// The owning news id (FK to the parent aggregate).
    pub news_id: NewsId,
    /// The owning school.
    pub school_id: SchoolId,
    /// The revision body.
    pub body: String,
    /// The revision number.
    pub revision_number: u32,
    /// The creation timestamp.
    pub created_at: DateTime<Utc>,
    /// The user who created the revision.
    pub created_by: UserId,
}

// =============================================================================
// ContentRevision (owned by Content)
// =============================================================================

/// A historical snapshot of a [`Content`](crate::aggregate::Content)
/// body. Revisions are append-only.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContentRevision {
    /// The typed id.
    pub id: ContentRevisionId,
    /// The owning content id (FK to the parent aggregate).
    pub content_id: ContentId,
    /// The owning school.
    pub school_id: SchoolId,
    /// The revision body.
    pub body: String,
    /// The revision number.
    pub revision_number: u32,
    /// The creation timestamp.
    pub created_at: DateTime<Utc>,
    /// The user who created the revision.
    pub created_by: UserId,
}

// =============================================================================
// ContentShareListAudience (owned by ContentShareList)
// =============================================================================

/// A materialized audience descriptor for a
/// [`ContentShareList`](crate::aggregate::ContentShareList).
/// Captured at dispatch time. The send_type + the matching
/// recipient id list. Per `docs/specs/cms/entities.md`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContentShareListAudience {
    /// The typed id.
    pub id: ContentShareListAudienceId,
    /// The owning share list id (FK to the parent aggregate).
    pub share_list_id: ContentShareListId,
    /// The owning school.
    pub school_id: SchoolId,
    /// The role ids (used when `send_type = G`).
    pub role_ids: Vec<Uuid>,
    /// The user ids (used when `send_type = I`).
    pub user_ids: Vec<Uuid>,
    /// The class id (used when `send_type = C`).
    pub class_id: Option<Uuid>,
    /// The section ids (used when `send_type = C`).
    pub section_ids: Vec<Uuid>,
    /// The creation timestamp.
    pub created_at: DateTime<Utc>,
    /// The user who materialised the audience.
    pub created_by: UserId,
}

// =============================================================================
// ContentShareListContent (owned by ContentShareList)
// =============================================================================

/// A join between a [`ContentShareList`](crate::aggregate::ContentShareList)
/// and a [`Content`](crate::aggregate::Content). The list has
/// many contents; each content appears in many lists.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContentShareListContent {
    /// The typed id.
    pub id: ContentShareListContentId,
    /// The owning share list id (FK to the parent aggregate).
    pub share_list_id: ContentShareListId,
    /// The content id being shared.
    pub content_id: ContentId,
    /// The owning school.
    pub school_id: SchoolId,
    /// The position of the content within the list (0-indexed).
    pub position: u32,
    /// The creation timestamp.
    pub created_at: DateTime<Utc>,
    /// The user who added the content to the list.
    pub created_by: UserId,
}

use uuid::Uuid;

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::dbg_macro
)]
mod tests {
    use super::*;
    use crate::value_objects::{FileReference, PublishDate, Slug};
    use chrono::{DateTime, Utc};
    use educore_academic::prelude::Identifier as _;
    use educore_core::ids::{SchoolId, UserId};

    #[test]
    fn news_image_carries_image_and_optional_thumb() {
        let school = SchoolId::from_uuid(uuid::Uuid::now_v7());
        let news_id = NewsId::new(school, uuid::Uuid::now_v7());
        let image_id = NewsImageId::new(school, uuid::Uuid::now_v7());
        let file = FileReference::new("image-key").unwrap();
        let img = NewsImage {
            id: image_id,
            news_id,
            school_id: school,
            image: file.clone(),
            image_thumb: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            created_by: UserId::from_uuid(uuid::Uuid::now_v7()),
            updated_by: UserId::from_uuid(uuid::Uuid::now_v7()),
        };
        assert_eq!(img.image.as_str(), "image-key");
        assert!(img.image_thumb.is_none());
    }

    #[test]
    fn page_revision_carries_body_and_number() {
        let school = SchoolId::from_uuid(uuid::Uuid::now_v7());
        let page_id = PageId::new(school, uuid::Uuid::now_v7());
        let rev_id = PageRevisionId::new(school, uuid::Uuid::now_v7());
        let r = PageRevision {
            id: rev_id,
            page_id,
            school_id: school,
            body: "body".to_owned(),
            revision_number: 1,
            created_at: Utc::now(),
            created_by: UserId::from_uuid(uuid::Uuid::now_v7()),
        };
        assert_eq!(r.body, "body");
        assert_eq!(r.revision_number, 1);
    }

    #[test]
    fn news_revision_carries_body_and_number() {
        let school = SchoolId::from_uuid(uuid::Uuid::now_v7());
        let news_id = NewsId::new(school, uuid::Uuid::now_v7());
        let rev_id = NewsRevisionId::new(school, uuid::Uuid::now_v7());
        let r = NewsRevision {
            id: rev_id,
            news_id,
            school_id: school,
            body: "body".to_owned(),
            revision_number: 1,
            created_at: Utc::now(),
            created_by: UserId::from_uuid(uuid::Uuid::now_v7()),
        };
        assert_eq!(r.body, "body");
    }

    #[test]
    fn content_revision_carries_body_and_number() {
        let school = SchoolId::from_uuid(uuid::Uuid::now_v7());
        let content_id = ContentId::new(school, uuid::Uuid::now_v7());
        let rev_id = ContentRevisionId::new(school, uuid::Uuid::now_v7());
        let r = ContentRevision {
            id: rev_id,
            content_id,
            school_id: school,
            body: "body".to_owned(),
            revision_number: 1,
            created_at: Utc::now(),
            created_by: UserId::from_uuid(uuid::Uuid::now_v7()),
        };
        assert_eq!(r.body, "body");
    }

    #[test]
    fn content_share_list_audience_carries_role_and_user_ids() {
        let school = SchoolId::from_uuid(uuid::Uuid::now_v7());
        let list_id = ContentShareListId::new(school, uuid::Uuid::now_v7());
        let id = ContentShareListAudienceId::new(school, uuid::Uuid::now_v7());
        let a = ContentShareListAudience {
            id,
            share_list_id: list_id,
            school_id: school,
            role_ids: vec![uuid::Uuid::now_v7()],
            user_ids: vec![],
            class_id: None,
            section_ids: vec![],
            created_at: Utc::now(),
            created_by: UserId::from_uuid(uuid::Uuid::now_v7()),
        };
        assert_eq!(a.role_ids.len(), 1);
        assert!(a.user_ids.is_empty());
    }

    #[test]
    fn content_share_list_content_carries_position() {
        let school = SchoolId::from_uuid(uuid::Uuid::now_v7());
        let list_id = ContentShareListId::new(school, uuid::Uuid::now_v7());
        let content_id = ContentId::new(school, uuid::Uuid::now_v7());
        let id = ContentShareListContentId::new(school, uuid::Uuid::now_v7());
        let c = ContentShareListContent {
            id,
            share_list_id: list_id,
            content_id,
            school_id: school,
            position: 3,
            created_at: Utc::now(),
            created_by: UserId::from_uuid(uuid::Uuid::now_v7()),
        };
        assert_eq!(c.position, 3);
    }

    // Anchor: prevent unused-import warnings if a future edit
    // removes the only call site.
    #[allow(dead_code)]
    fn _anchor() {
        let _ = PublishDate::new(chrono::NaiveDate::from_ymd_opt(2026, 6, 1).unwrap());
        let _ = Slug::new("anchor").unwrap();
    }
}
