//! Typed identifiers for the Educore engine.
//!
//! Every aggregate and every cross-cutting concept is keyed by a typed
//! identifier. Two identifiers that share the same underlying UUID but
//! have different Rust types (e.g. `SchoolId` vs. `UserId`) are
//! **not** interchangeable: the type system catches cross-aggregate id
//! confusion at compile time.
//!
//! All identifiers are UUIDv7 (time-ordered, globally unique). They are
//! generated by the [`IdGenerator`](crate::id_gen::IdGenerator) port
//! and are opaque to consumers — strings are never parsed.
//!
//! See:
//! - `docs/schemas/tenancy-schema.md` § 2 (SchoolId)
//! - `docs/schemas/event-schema.md` § 1.1 (EventId, CorrelationId)
//! - `docs/schemas/command-schema.md` § 1.2 (IdempotencyKey)

use std::fmt;
use std::hash::Hash;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::error::{DomainError, Result};

/// The actor that triggered a state change.
///
/// Per `docs/schemas/database-schema.md` § 5 and `docs/schemas/event-schema.md`
/// § 1.1, system-inserted rows (bootstrap, migrations, scheduled jobs) use a
/// well-known id; everything else uses a real `UserId`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct UserId(pub Uuid);

/// The tenant root. A `SchoolId` is the unit of tenancy; every other
/// aggregate anchors to a `SchoolId` (either as part of its typed
/// identifier or as a separate column).
///
/// Per `docs/schemas/tenancy-schema.md` § 2: immutable for the lifetime
/// of the school; opaque to consumers; UUIDv7.
///
/// Aggregates that belong to a school embed `SchoolId` in their typed
/// identifier (e.g. `StudentId(SchoolId, Uuid)`) so that
/// cross-tenant references become compile-time errors.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SchoolId(pub Uuid);

/// A domain event identifier.
///
/// Per `docs/schemas/event-schema.md` § 1.1: UUIDv7, the canonical
/// primary key of the event in the log. Two events MUST NOT share an
/// `EventId`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct EventId(pub Uuid);

/// A correlation identifier: the id of the request or workflow that
/// initiated the chain of events.
///
/// Per `docs/schemas/event-schema.md` § 1.1: set by the inbound
/// command, propagated through every event in the same request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct CorrelationId(pub Uuid);

/// A session identifier.
///
/// Optional in `TenantContext`. Carries the consumer's session
/// boundary (which may differ from the request's correlation).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SessionId(pub Uuid);

/// A caller-provided idempotency token.
///
/// Per `docs/schemas/command-schema.md` § 1.2 and
/// `docs/decisions/ADR-014-Idempotency.md`: two commands with the same
/// `IdempotencyKey` against the same `school_id` and `command_type`
/// MUST produce the same result and emit no additional events on
/// replay.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct IdempotencyKey(pub Uuid);

/// Marker trait for typed identifiers.
///
/// Implemented by every wrapper around `Uuid` in this module. The
/// trait exists so generic code (e.g. `StudentId(SchoolId, Uuid)`)
/// can constrain its inner school id without naming a specific
/// concrete type.
pub trait Identifier: Clone + Copy + PartialEq + Eq + Hash + fmt::Debug + fmt::Display {
    /// Returns the inner UUID.
    fn as_uuid(&self) -> Uuid;

    /// Returns a new typed identifier wrapping the given UUID.
    ///
    /// Constructors are infallible at the type level; if the caller
    /// wants to validate (e.g. "is this a v7 UUID?") they call
    /// [`from_uuid_checked`].
    fn from_uuid(uuid: Uuid) -> Self;

    /// Constructs a typed identifier from a UUID, validating that
    /// the UUID is a v7 (time-ordered) value.
    ///
    /// Returns `Err(DomainError::Validation)` if the UUID is not v7.
    fn from_uuid_checked(uuid: Uuid) -> Result<Self> {
        if uuid.get_version_num() == 7 {
            Ok(Self::from_uuid(uuid))
        } else {
            Err(DomainError::Validation(format!(
                "expected UUIDv7 identifier, got version {}",
                uuid.get_version_num()
            )))
        }
    }
}

impl Identifier for UserId {
    #[inline]
    fn as_uuid(&self) -> Uuid {
        self.0
    }
    #[inline]
    fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }
}

impl Identifier for SchoolId {
    #[inline]
    fn as_uuid(&self) -> Uuid {
        self.0
    }
    #[inline]
    fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }
}

impl Identifier for EventId {
    #[inline]
    fn as_uuid(&self) -> Uuid {
        self.0
    }
    #[inline]
    fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }
}

impl Identifier for CorrelationId {
    #[inline]
    fn as_uuid(&self) -> Uuid {
        self.0
    }
    #[inline]
    fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }
}

impl Identifier for SessionId {
    #[inline]
    fn as_uuid(&self) -> Uuid {
        self.0
    }
    #[inline]
    fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }
}

impl Identifier for IdempotencyKey {
    #[inline]
    fn as_uuid(&self) -> Uuid {
        self.0
    }
    #[inline]
    fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }
}

impl fmt::Display for UserId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl fmt::Display for SchoolId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl fmt::Display for EventId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl fmt::Display for CorrelationId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl fmt::Display for SessionId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl fmt::Display for IdempotencyKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl From<Uuid> for UserId {
    fn from(u: Uuid) -> Self {
        Self(u)
    }
}

impl From<Uuid> for SchoolId {
    fn from(u: Uuid) -> Self {
        Self(u)
    }
}

impl From<Uuid> for EventId {
    fn from(u: Uuid) -> Self {
        Self(u)
    }
}

impl From<Uuid> for CorrelationId {
    fn from(u: Uuid) -> Self {
        Self(u)
    }
}

impl From<Uuid> for SessionId {
    fn from(u: Uuid) -> Self {
        Self(u)
    }
}

impl From<Uuid> for IdempotencyKey {
    fn from(u: Uuid) -> Self {
        Self(u)
    }
}

/// The well-known system actor used for system-inserted rows, jobs,
/// and migrations. Per `docs/schemas/database-schema.md` § 5 the
/// constant is named `SYSTEM_USER_ID`.
///
/// A v7 UUID with all-zero timestamp and a fixed random suffix so
/// the id is recognisable in logs and the audit trail. The value is
/// stable for the lifetime of the engine — consumers that need to
/// compare against "this was a system change" should reference this
/// constant rather than the literal.
pub const SYSTEM_USER_ID: UserId = UserId(Uuid::from_bytes([
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x70, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
]));

/// The well-known "platform" school id used for global aggregates
/// (e.g. `Country`, `Currency` lookup tables) that are not anchored
/// to a single school.
///
/// Per `docs/specs/platform/overview.md` invariants: aggregates
/// without a school are global; the platform school id is the
/// anchor for those rows.
pub const PLATFORM_SCHOOL_ID: SchoolId = SchoolId(Uuid::from_bytes([
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x70, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
]));

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::dbg_macro
)]
mod tests {
    use super::*;

    #[test]
    fn from_uuid_checked_accepts_v7() {
        let v7 = Uuid::now_v7();
        let id = SchoolId::from_uuid_checked(v7).unwrap();
        assert_eq!(id.as_uuid(), v7);
    }

    #[test]
    fn from_uuid_checked_rejects_v4() {
        let v4 = Uuid::new_v4();
        let err = SchoolId::from_uuid_checked(v4).unwrap_err();
        assert!(matches!(err, DomainError::Validation(_)));
    }

    #[test]
    fn system_user_id_is_stable() {
        let a = SYSTEM_USER_ID.as_uuid();
        let b = Uuid::from_bytes([
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x70, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x01,
        ]);
        assert_eq!(a, b);
        assert_eq!(a.get_version_num(), 7);
    }

    #[test]
    fn platform_school_id_is_stable() {
        let a = PLATFORM_SCHOOL_ID.as_uuid();
        let b = Uuid::from_bytes([
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x70, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x02,
        ]);
        assert_eq!(a, b);
        assert_eq!(a.get_version_num(), 7);
    }

    #[test]
    fn display_matches_inner_uuid() {
        let v7 = Uuid::now_v7();
        let id = SchoolId::from_uuid(v7);
        assert_eq!(id.to_string(), v7.to_string());
    }
}
