//! The shared query AST consumed by the `#[derive(DomainQuery)]`
//! macro and emitted by storage adapters.
//!
//! Per `docs/query_layer.md`:
//!
//! - The AST is **the only contract** between the engine and a
//!   storage adapter. Adapters translate the AST into the storage
//!   dialect; the macro never produces SQL/NoSQL/specific syntax.
//! - The AST is **closed**: the variants are fixed and the
//!   `FieldKind` parameter is bounded by the `Field` trait, so the
//!   macro emission and the storage adapter's translator are
//!   exhaustive at compile time.
//! - `QueryNode` is **not** runtime-introspectable: there is no
//!   `Box<dyn Any>` and no `serde_json::Value` here. The macro
//!   guarantees the field set at compile time.
//!
//! The `EntityDescriptor` (the macro's table/column/index output)
//! lives in `educore-query-derive`; this module hosts only the
//! *runtime* AST types shared by every engine crate.

use std::fmt;
use std::hash::Hash;

use serde::{Deserialize, Serialize};

use crate::ids::SchoolId;

/// Marker trait for typed field identifiers.
///
/// Every per-aggregate `StudentField`, `ClassField`, `ExamField`,
/// ... is an enum generated by `#[derive(DomainQuery)]`. The
/// generated enum implements this trait so the `QueryNode<F>`
/// AST is generic over any aggregate.
pub trait Field: Clone + Copy + PartialEq + Eq + Hash + fmt::Debug {
    /// A stable wire name for the field. Storage adapters use this
    /// to map the typed identifier to a column name. The macro
    /// generates this implementation.
    fn column_name(self) -> &'static str;
}

/// Marker trait for field enums that declare at least one relation
/// and therefore have a `*Relation` enum emitted by
/// `#[derive(DomainQuery)]`.
///
/// The trait associates the parent `*Field` enum with its sibling
/// `*Relation` enum so that `QueryNode<F>::HasRelation` can carry a
/// strongly-typed relation value. It is implemented by the macro
/// only for structs that declare at least one field with
/// `#[query(relation = "...", builder = "...")]`. Structs without
/// relations do not need to implement it.
pub trait HasRelations: Field {
    /// The relation enum emitted alongside `Self`. The
    /// `#[derive(DomainQuery)]` macro emits a definition of the
    /// form `pub type Relation = StudentRelation;`.
    type Relation: Clone + Copy + PartialEq + Eq + Hash + fmt::Debug;
}

/// A filter value carried by `QueryNode::Eq`, `In`, `Between`, etc.
///
/// The engine never uses `serde_json::Value` for filter values
/// (per `AGENTS.md` and `docs/code-standards.md`). Each storage
/// adapter translates the typed variant into its dialect.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Value {
    /// A null value, used in `IS NULL` / `IS NOT NULL` only.
    Null,
    /// A boolean value.
    Bool(bool),
    /// A 64-bit signed integer.
    I64(i64),
    /// A 64-bit unsigned integer.
    U64(u64),
    /// A 64-bit floating point.
    F64(f64),
    /// A string value.
    String(String),
    /// A byte string (BLOB).
    Bytes(Vec<u8>),
    /// A typed identifier (UUID). The wire form is the canonical
    /// 36-char hyphenated UUID string per RFC 4122.
    Uuid(uuid::Uuid),
    /// A UTC timestamp. The wire form is RFC 3339 with microsecond
    /// precision ending in `Z`.
    Timestamp(crate::value_objects::Timestamp),
    /// A list of values, used by `In` / `NotIn`.
    List(Vec<Value>),
}

impl Eq for Value {}

impl Value {
    /// Returns `true` if the value is `Value::Null`. Useful for
    /// adapters that need to short-circuit `IS NULL` checks.
    #[must_use]
    pub const fn is_null(&self) -> bool {
        matches!(self, Self::Null)
    }
}

impl From<bool> for Value {
    fn from(v: bool) -> Self {
        Self::Bool(v)
    }
}

impl From<i64> for Value {
    fn from(v: i64) -> Self {
        Self::I64(v)
    }
}

impl From<i32> for Value {
    fn from(v: i32) -> Self {
        Self::I64(i64::from(v))
    }
}

impl From<u64> for Value {
    fn from(v: u64) -> Self {
        Self::U64(v)
    }
}

impl From<u32> for Value {
    fn from(v: u32) -> Self {
        Self::U64(u64::from(v))
    }
}

impl From<f64> for Value {
    fn from(v: f64) -> Self {
        Self::F64(v)
    }
}

impl From<String> for Value {
    fn from(v: String) -> Self {
        Self::String(v)
    }
}

impl From<&str> for Value {
    fn from(v: &str) -> Self {
        Self::String(v.to_owned())
    }
}

impl From<Vec<u8>> for Value {
    fn from(v: Vec<u8>) -> Self {
        Self::Bytes(v)
    }
}

impl From<uuid::Uuid> for Value {
    fn from(v: uuid::Uuid) -> Self {
        Self::Uuid(v)
    }
}

impl From<crate::value_objects::Timestamp> for Value {
    fn from(v: crate::value_objects::Timestamp) -> Self {
        Self::Timestamp(v)
    }
}

impl From<Vec<Value>> for Value {
    fn from(v: Vec<Value>) -> Self {
        Self::List(v)
    }
}

/// A `LIKE` / `ILIKE` pattern. The pattern uses SQL `%` and `_`
/// wildcards; the storage adapter translates them to the dialect's
/// native pattern syntax.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Pattern(String);

impl Pattern {
    /// Constructs a `Pattern` from a raw string. The string is
    /// not validated: storage adapters are responsible for
    /// rejecting patterns that contain unsupported metacharacters.
    #[must_use]
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    /// Returns the pattern as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for Pattern {
    fn from(s: &str) -> Self {
        Self(s.to_owned())
    }
}

impl From<String> for Pattern {
    fn from(s: String) -> Self {
        Self(s)
    }
}

impl fmt::Display for Pattern {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

/// The dialect-agnostic query AST.
///
/// Every filter, every join, every nested `where_has` collapses
/// into a `QueryNode<F>`. Storage adapters translate this into the
/// dialect's execution plan. The variant set is closed: adding a
/// new filter shape requires both a macro change and an adapter
/// change, which is intentional.
///
/// The AST is an in-memory type only; it is not serialised to a
/// wire format. Consumers that need to ship a query to a remote
/// engine (e.g. over the sync wire protocol) translate the AST
/// into their transport's command envelope — the AST is the
/// local, pre-translation shape.
#[derive(Debug, Clone, PartialEq)]
pub enum QueryNode<F: Field> {
    /// `field = value`
    Eq(F, Value),
    /// `field <> value`
    Ne(F, Value),
    /// `field < value`
    Lt(F, Value),
    /// `field <= value`
    Lte(F, Value),
    /// `field > value`
    Gt(F, Value),
    /// `field >= value`
    Gte(F, Value),
    /// `field IN (values...)`
    In(F, Vec<Value>),
    /// `field NOT IN (values...)`
    NotIn(F, Vec<Value>),
    /// `field BETWEEN lo AND hi`
    Between(F, Value, Value),
    /// `field IS NULL`
    IsNull(F),
    /// `field IS NOT NULL`
    IsNotNull(F),
    /// `field LIKE pattern` (case-sensitive, SQL semantics)
    Like(F, Pattern),
    /// `field ILIKE pattern` (case-insensitive, SQL semantics)
    ILike(F, Pattern),
    /// Conjunction: `left AND right`. Both sides are `QueryNode`s.
    And(Box<QueryNode<F>>, Box<QueryNode<F>>),
    /// Disjunction: `left OR right`.
    Or(Box<QueryNode<F>>, Box<QueryNode<F>>),
    /// Negation: `NOT inner`.
    Not(Box<QueryNode<F>>),
    /// Nested relational filter (`where_has`). The inner
    /// `QueryNode<G>` is built against the related aggregate's
    /// field enum, where `G: Field` is the related entity's
    /// `FieldKind`.
    ///
    /// Storage adapters translate this into a join, an `EXISTS`
    /// subquery, or a `TRAVERSE` clause depending on the dialect.
    HasRelation(Relation, Box<QueryNode<RelationalField>>),
}

impl<F: Field> QueryNode<F> {
    /// Returns `true` if the node contains no filters
    /// (a degenerate `And(And(...), And(...))` with all-empty
    /// children collapses to this in the macro emission).
    #[must_use]
    pub fn is_empty(&self) -> bool {
        match self {
            Self::And(a, b) => a.is_empty() && b.is_empty(),
            Self::Or(a, b) => a.is_empty() && b.is_empty(),
            Self::Not(inner) => inner.is_empty(),
            _ => false,
        }
    }

    /// Collects every field referenced anywhere in the tree.
    pub fn referenced_fields(&self, out: &mut Vec<F>) {
        match self {
            Self::Eq(f, _)
            | Self::Ne(f, _)
            | Self::Lt(f, _)
            | Self::Lte(f, _)
            | Self::Gt(f, _)
            | Self::Gte(f, _)
            | Self::In(f, _)
            | Self::NotIn(f, _)
            | Self::Between(f, _, _)
            | Self::IsNull(f)
            | Self::IsNotNull(f)
            | Self::Like(f, _)
            | Self::ILike(f, _) => out.push(*f),
            Self::And(a, b) | Self::Or(a, b) => {
                a.referenced_fields(out);
                b.referenced_fields(out);
            }
            Self::Not(inner) => inner.referenced_fields(out),
            // HasRelation carries a different field type; the
            // caller is responsible for walking it via
            // `referenced_relation_fields`.
            Self::HasRelation(_, _) => {}
        }
    }
}

/// Order direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderDirection {
    /// Ascending (`ORDER BY ... ASC`).
    Asc,
    /// Descending (`ORDER BY ... DESC`).
    Desc,
}

impl fmt::Display for OrderDirection {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Asc => "ASC",
            Self::Desc => "DESC",
        })
    }
}

/// A single `ORDER BY` clause.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct OrderNode<F: Field> {
    /// The field to order by.
    pub field: F,
    /// The direction.
    pub direction: OrderDirection,
}

impl<F: Field> OrderNode<F> {
    /// Constructs an ascending `OrderNode`.
    #[must_use]
    pub const fn asc(field: F) -> Self {
        Self {
            field,
            direction: OrderDirection::Asc,
        }
    }

    /// Constructs a descending `OrderNode`.
    #[must_use]
    pub const fn desc(field: F) -> Self {
        Self {
            field,
            direction: OrderDirection::Desc,
        }
    }
}

/// The shape of a relation used by `QueryNode::HasRelation` and by
/// the `with` hydration directive.
///
/// The macro emits one `Relation` variant per declared
/// `#[query(relation = "...")]` attribute.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Relation {
    /// The macro-assigned relation id (the value of the
    /// `relation = "..."` attribute).
    pub id: u32,
    /// The singular name of the related aggregate (e.g. `parent`,
    /// `class`).
    pub name: &'static str,
}

/// A placeholder `Field` used inside `QueryNode::HasRelation`. The
/// macro emission replaces this with the actual related
/// aggregate's `FieldKind` at the call site; adapters use it to
/// distinguish relation-nested fields from parent fields in their
/// translator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RelationalField;

impl Field for RelationalField {
    fn column_name(self) -> &'static str {
        // Relations address their related aggregate's columns by
        // the related column's name, not by the parent's. The
        // macro replaces this method with the proper resolution
        // at the call site (via `HasRelations::Field`); the
        // generic placeholder is used only when the AST is
        // serialised for diagnostics.
        "<relation>"
    }
}

/// Pagination is stored on the `Query<F>` wrapper, not in
/// `QueryNode<F>`, because pagination is not a filter. The
/// wrapper struct is defined in the macro emission; the engine
/// only re-exports the type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Page {
    /// Zero-based offset.
    pub offset: u32,
    /// Maximum rows.
    pub limit: u32,
}

impl Page {
    /// Constructs a `Page(offset, limit)`.
    #[must_use]
    pub const fn new(offset: u32, limit: u32) -> Self {
        Self { offset, limit }
    }
}

/// Tenant scope attached to every query. Storage adapters MUST
/// inject `school_id = $scope.school_id` (or the dialect's
/// equivalent) into the query plan. Per
/// `docs/schemas/tenancy-schema.md` § 4.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct TenantScope {
    /// The active school. Mandatory.
    pub school_id: SchoolId,
}

impl TenantScope {
    /// Constructs a `TenantScope` for the given school.
    #[must_use]
    pub const fn new(school_id: SchoolId) -> Self {
        Self { school_id }
    }
}

/// Convert any `QueryNode<F>` (where `F: Field`) into a
/// `QueryNode<RelationalField>`. The placeholder `RelationalField`
/// is used in `QueryNode::HasRelation` because the related
/// aggregate's field type is unknown to the parent builder; the
/// storage adapter resolves the actual column names at translation
/// time via the `Relation::name` in the `HasRelation` variant.
///
/// This is a free function (not an `impl From<...> for ...`) because
/// the blanket `impl<T> From<T> for T` in core would conflict with
/// any generic `impl<F: Field> From<QueryNode<F>> for
/// QueryNode<RelationalField>>` when `F = RelationalField`. The
/// `#[derive(DomainQuery)]` macro calls this function inside
/// `where_has_<relation>` to wrap the related builder's compiled
/// AST in a `HasRelation` node. The blanket `From<T> for T` covers
/// the trivial `F = RelationalField` case, so callers never see
/// the conflict.
pub fn to_relational_node<F: Field>(node: QueryNode<F>) -> QueryNode<RelationalField> {
    match node {
        QueryNode::Eq(_, v) => QueryNode::Eq(RelationalField, v),
        QueryNode::Ne(_, v) => QueryNode::Ne(RelationalField, v),
        QueryNode::Lt(_, v) => QueryNode::Lt(RelationalField, v),
        QueryNode::Lte(_, v) => QueryNode::Lte(RelationalField, v),
        QueryNode::Gt(_, v) => QueryNode::Gt(RelationalField, v),
        QueryNode::Gte(_, v) => QueryNode::Gte(RelationalField, v),
        QueryNode::In(_, v) => QueryNode::In(RelationalField, v),
        QueryNode::NotIn(_, v) => QueryNode::NotIn(RelationalField, v),
        QueryNode::Between(_, lo, hi) => QueryNode::Between(RelationalField, lo, hi),
        QueryNode::IsNull(_) => QueryNode::IsNull(RelationalField),
        QueryNode::IsNotNull(_) => QueryNode::IsNotNull(RelationalField),
        QueryNode::Like(_, p) => QueryNode::Like(RelationalField, p),
        QueryNode::ILike(_, p) => QueryNode::ILike(RelationalField, p),
        QueryNode::And(a, b) => QueryNode::And(
            Box::new(to_relational_node(*a)),
            Box::new(to_relational_node(*b)),
        ),
        QueryNode::Or(a, b) => QueryNode::Or(
            Box::new(to_relational_node(*a)),
            Box::new(to_relational_node(*b)),
        ),
        QueryNode::Not(inner) => QueryNode::Not(Box::new(to_relational_node(*inner))),
        QueryNode::HasRelation(rel, inner) => QueryNode::HasRelation(rel, inner),
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::dbg_macro
)]
mod tests {
    use super::*;

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    enum DummyField {
        Name,
        Age,
    }

    impl Field for DummyField {
        fn column_name(self) -> &'static str {
            match self {
                Self::Name => "name",
                Self::Age => "age",
            }
        }
    }

    #[test]
    fn value_is_constructible_from_primitives() {
        let _ = Value::from(42_i64);
        let _ = Value::from("hello");
        let _ = Value::from(true);
        let _ = Value::from(std::f64::consts::PI);
        let _ = Value::from(uuid::Uuid::nil());
    }

    #[test]
    fn value_from_i32_promotes_to_i64() {
        let v = Value::from(7_i32);
        assert!(matches!(v, Value::I64(7)));
    }

    #[test]
    fn value_from_u32_promotes_to_u64() {
        let v = Value::from(7_u32);
        assert!(matches!(v, Value::U64(7)));
    }

    #[test]
    fn list_value_holds_values() {
        let list = Value::List(vec![Value::from(1_i64), Value::from(2_i64)]);
        assert!(matches!(list, Value::List(_)));
    }

    #[test]
    fn pattern_from_str() {
        let p = Pattern::from("%foo%");
        assert_eq!(p.as_str(), "%foo%");
    }

    #[test]
    fn order_node_asc_and_desc() {
        let a = OrderNode::asc(DummyField::Name);
        assert_eq!(a.direction, OrderDirection::Asc);
        let d = OrderNode::desc(DummyField::Name);
        assert_eq!(d.direction, OrderDirection::Desc);
    }

    #[test]
    fn order_direction_display() {
        assert_eq!(OrderDirection::Asc.to_string(), "ASC");
        assert_eq!(OrderDirection::Desc.to_string(), "DESC");
    }

    #[test]
    fn query_node_referenced_fields() {
        let node = QueryNode::And(
            Box::new(QueryNode::Eq(DummyField::Name, Value::from("a"))),
            Box::new(QueryNode::Gt(DummyField::Age, Value::from(18_i64))),
        );
        let mut fields = Vec::new();
        node.referenced_fields(&mut fields);
        assert_eq!(fields, vec![DummyField::Name, DummyField::Age]);
    }

    #[test]
    fn query_node_is_empty_for_pure_and() {
        let empty = QueryNode::And(
            Box::new(QueryNode::IsNull(DummyField::Name)),
            Box::new(QueryNode::IsNotNull(DummyField::Age)),
        );
        // `is_empty` returns true only when ALL leaves are
        // degenerate; an `IsNull` is not degenerate. So this
        // returns false.
        assert!(!empty.is_empty());
    }

    #[test]
    fn field_column_name_round_trip() {
        assert_eq!(DummyField::Name.column_name(), "name");
        assert_eq!(DummyField::Age.column_name(), "age");
    }
}
