// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: cross-cutting/platform/src/services.rs (2 fns)
//
// Add to cross-cutting/platform/src/services.rs and cross-cutting/platform/src/lib.rs.
// Template: Wave 192 dispatch_admit_student pattern.

use educore_dispatcher::CommandDispatcher;

impl educore_dispatcher::CommandBounds for CreateSchoolCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.school.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "school" }
}

/// Dispatcher wrapper for [`create_school`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_school<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateSchoolCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(School, SchoolCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_school::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RegisterUserCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.user.register" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "register" }
    fn target_type(&self) -> &'static str { "user" }
}

/// Dispatcher wrapper for [`register_user`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_register_user<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RegisterUserCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(User, UserRegistered)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            register_user::<C, G>(cmd,
        uniqueness,)
        })
        .await
}

