// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/academic/src/commands.rs (91 commands)
//
// Each impl block derives action/target from the command name.
// Capability string is inferred from the crate path.
// Skip commands without a `tenant: TenantContext` field.
//
// Wire into domains/academic/src/commands.rs (append at end).
// Template: Wave 192 AdmitStudentCommand impl.

impl educore_dispatcher::CommandBounds for AdmitStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.student.admit" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "admit" }
    fn target_type(&self) -> &'static str { "student" }
}

impl educore_dispatcher::CommandBounds for UpdateStudentProfileCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.studentProfile.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "studentProfile" }
}

impl educore_dispatcher::CommandBounds for SuspendStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.student.suspend" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "suspend" }
    fn target_type(&self) -> &'static str { "student" }
}

impl educore_dispatcher::CommandBounds for ReinstateStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.student.reinstate" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "reinstate" }
    fn target_type(&self) -> &'static str { "student" }
}

impl educore_dispatcher::CommandBounds for WithdrawStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.student.withdraw" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "withdraw" }
    fn target_type(&self) -> &'static str { "student" }
}

impl educore_dispatcher::CommandBounds for TransferStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.student.transfer" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "transfer" }
    fn target_type(&self) -> &'static str { "student" }
}

impl educore_dispatcher::CommandBounds for PromoteStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.student.promote" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "promote" }
    fn target_type(&self) -> &'static str { "student" }
}

impl educore_dispatcher::CommandBounds for GraduateStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.student.graduate" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "graduate" }
    fn target_type(&self) -> &'static str { "student" }
}

impl educore_dispatcher::CommandBounds for CreateClassCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.class.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "class" }
}

impl educore_dispatcher::CommandBounds for UpdateClassCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.class.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "class" }
}

impl educore_dispatcher::CommandBounds for SetOptionalSubjectGpaThresholdCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.optionalSubjectGpaThreshold.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "optionalSubjectGpaThreshold" }
}

impl educore_dispatcher::CommandBounds for DeleteClassCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.class.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "class" }
}

impl educore_dispatcher::CommandBounds for CreateSectionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.section.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "section" }
}

impl educore_dispatcher::CommandBounds for UpdateSectionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.section.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "section" }
}

impl educore_dispatcher::CommandBounds for DeleteSectionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.section.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "section" }
}

impl educore_dispatcher::CommandBounds for CreateSubjectCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.subject.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "subject" }
}

impl educore_dispatcher::CommandBounds for UpdateSubjectCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.subject.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "subject" }
}

impl educore_dispatcher::CommandBounds for DeleteSubjectCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.subject.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "subject" }
}

impl educore_dispatcher::CommandBounds for CreateAcademicYearCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.academicYear.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "academicYear" }
}

impl educore_dispatcher::CommandBounds for UpdateAcademicYearDatesCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.academicYearDat.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "academicYearDat" }
}

impl educore_dispatcher::CommandBounds for SetCurrentAcademicYearCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.currentAcademicYear.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "currentAcademicYear" }
}

impl educore_dispatcher::CommandBounds for CloseAcademicYearCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.academicYear.close" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "close" }
    fn target_type(&self) -> &'static str { "academicYear" }
}

// SKIP RegisterGuardianCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for LinkGuardianToStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.guardianToStudent.link" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "link" }
    fn target_type(&self) -> &'static str { "guardianToStudent" }
}

impl educore_dispatcher::CommandBounds for UnlinkGuardianFromStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.guardianFromStudent.unlink" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unlink" }
    fn target_type(&self) -> &'static str { "guardianFromStudent" }
}

impl educore_dispatcher::CommandBounds for MarkPrimaryGuardianCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.primaryGuardian.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "primaryGuardian" }
}

impl educore_dispatcher::CommandBounds for UpdateGuardianContactCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.guardianContact.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "guardianContact" }
}

impl educore_dispatcher::CommandBounds for RetireGuardianCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.guardian.retire" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "retire" }
    fn target_type(&self) -> &'static str { "guardian" }
}

impl educore_dispatcher::CommandBounds for CreateClassSectionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.classSection.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "classSection" }
}

impl educore_dispatcher::CommandBounds for CreateClassRoutineCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.classRoutine.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "classRoutine" }
}

impl educore_dispatcher::CommandBounds for UpdateClassRoutinePeriodCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.classRoutinePeriod.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "classRoutinePeriod" }
}

impl educore_dispatcher::CommandBounds for SwapClassRoutinePeriodsCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.classRoutinePeriod.swap" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "swap" }
    fn target_type(&self) -> &'static str { "classRoutinePeriod" }
}

impl educore_dispatcher::CommandBounds for DeleteClassRoutineCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.classRoutine.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "classRoutine" }
}

impl educore_dispatcher::CommandBounds for CreateHomeworkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.homework.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "homework" }
}

impl educore_dispatcher::CommandBounds for UpdateHomeworkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.homework.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "homework" }
}

impl educore_dispatcher::CommandBounds for CancelHomeworkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.homework.cancel" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "cancel" }
    fn target_type(&self) -> &'static str { "homework" }
}

// SKIP CreateLessonPlanCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for RealCreateLessonPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.realCreateLessonPlan.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "realCreateLessonPlan" }
}

impl educore_dispatcher::CommandBounds for UpdateLessonPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.lessonPlan.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "lessonPlan" }
}

impl educore_dispatcher::CommandBounds for MarkLessonPlanCompletedCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.lessonPlanCompleted.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "lessonPlanCompleted" }
}

impl educore_dispatcher::CommandBounds for AddSubTopicCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.addSubTopic.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "addSubTopic" }
}

impl educore_dispatcher::CommandBounds for DeleteLessonPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.lessonPlan.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "lessonPlan" }
}

// SKIP CreateLessonCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for RealCreateLessonCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.realCreateLesson.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "realCreateLesson" }
}

impl educore_dispatcher::CommandBounds for UpdateLessonCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.lesson.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "lesson" }
}

impl educore_dispatcher::CommandBounds for DeleteLessonCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.lesson.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "lesson" }
}

// SKIP CreateLessonTopicCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for RealCreateLessonTopicCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.realCreateLessonTopic.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "realCreateLessonTopic" }
}

impl educore_dispatcher::CommandBounds for MarkTopicCompletedCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.topicCompleted.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "topicCompleted" }
}

impl educore_dispatcher::CommandBounds for DeleteLessonTopicCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.lessonTopic.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "lessonTopic" }
}

// SKIP RecordStudentPromotionCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateStudentCategoryCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for RealCreateStudentCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.realCreateStudentCategory.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "realCreateStudentCategory" }
}

impl educore_dispatcher::CommandBounds for UpdateStudentCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.studentCategory.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "studentCategory" }
}

impl educore_dispatcher::CommandBounds for DeleteStudentCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.studentCategory.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "studentCategory" }
}

// SKIP CreateStudentGroupCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for RealCreateStudentGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.realCreateStudentGroup.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "realCreateStudentGroup" }
}

impl educore_dispatcher::CommandBounds for UpdateStudentGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.studentGroup.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "studentGroup" }
}

impl educore_dispatcher::CommandBounds for AddStudentToGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.addStudentToGroup.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "addStudentToGroup" }
}

impl educore_dispatcher::CommandBounds for RemoveStudentFromGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.removeStudentFromGroup.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "removeStudentFromGroup" }
}

impl educore_dispatcher::CommandBounds for DeleteStudentGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.studentGroup.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "studentGroup" }
}

// SKIP CreateRegistrationFieldCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for RealCreateRegistrationFieldCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.realCreateRegistrationField.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "realCreateRegistrationField" }
}

impl educore_dispatcher::CommandBounds for UpdateRegistrationFieldCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.registrationField.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "registrationField" }
}

impl educore_dispatcher::CommandBounds for DeleteRegistrationFieldCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.registrationField.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "registrationField" }
}

// SKIP CreateCertificateCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for RealCreateCertificateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.realCreateCertificate.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "realCreateCertificate" }
}

impl educore_dispatcher::CommandBounds for UpdateCertificateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.certificate.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "certificate" }
}

impl educore_dispatcher::CommandBounds for DeleteCertificateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.certificate.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "certificate" }
}

// SKIP CreateIdCardCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for RealCreateIdCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.realCreateIdCard.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "realCreateIdCard" }
}

impl educore_dispatcher::CommandBounds for UpdateIdCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.idCard.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "idCard" }
}

impl educore_dispatcher::CommandBounds for DeleteIdCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.idCard.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "idCard" }
}

impl educore_dispatcher::CommandBounds for AssignStudentToSectionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.studentToSection.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "studentToSection" }
}

impl educore_dispatcher::CommandBounds for ChangeStudentCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.changeStudentCategory.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "changeStudentCategory" }
}

impl educore_dispatcher::CommandBounds for AssignOptionalSubjectCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.optionalSubject.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "optionalSubject" }
}

impl educore_dispatcher::CommandBounds for UploadStudentDocumentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.uploadStudentDocument.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "uploadStudentDocument" }
}

impl educore_dispatcher::CommandBounds for AssignClassTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.classTeacher.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "classTeacher" }
}

impl educore_dispatcher::CommandBounds for AssignSubjectTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.subjectTeacher.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "subjectTeacher" }
}

impl educore_dispatcher::CommandBounds for AssignClassRoomCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.classRoom.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "classRoom" }
}

impl educore_dispatcher::CommandBounds for DeleteClassSectionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.classSection.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "classSection" }
}

impl educore_dispatcher::CommandBounds for AssignSubjectToClassCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.subjectToClass.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "subjectToClass" }
}

impl educore_dispatcher::CommandBounds for ReassignTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.teacher.reassign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "reassign" }
    fn target_type(&self) -> &'static str { "teacher" }
}

impl educore_dispatcher::CommandBounds for UnassignSubjectCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.subject.unassign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unassign" }
    fn target_type(&self) -> &'static str { "subject" }
}

impl educore_dispatcher::CommandBounds for SubmitHomeworkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.submitHomework.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "submitHomework" }
}

impl educore_dispatcher::CommandBounds for EvaluateHomeworkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.evaluateHomework.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "evaluateHomework" }
}

impl educore_dispatcher::CommandBounds for RegisterAdmissionQueryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.admissionQuery.register" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "register" }
    fn target_type(&self) -> &'static str { "admissionQuery" }
}

impl educore_dispatcher::CommandBounds for EnrollStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.enrollStudent.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "enrollStudent" }
}

impl educore_dispatcher::CommandBounds for SetRollNumberCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.rollNumber.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "rollNumber" }
}

impl educore_dispatcher::CommandBounds for SetDefaultRecordCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.defaultRecord.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "defaultRecord" }
}

impl educore_dispatcher::CommandBounds for MarkGraduateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "academic.graduate.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "graduate" }
}

// Generated: 81, Skipped (no tenant field): 10