// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/assessment/src/services.rs (13 fns)
//
// Add to domains/assessment/src/services.rs and domains/assessment/src/lib.rs.
// Template: Wave 192 dispatch_admit_student pattern.

use educore_dispatcher::CommandDispatcher;

impl educore_dispatcher::CommandBounds for CreateExamCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.exam.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "exam" }
}

/// Dispatcher wrapper for [`create_exam`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_exam<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateExamCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(Exam, ExamCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_exam::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for ScheduleExamCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.scheduleExam.schedule" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "schedule" }
    fn target_type(&self) -> &'static str { "scheduleExam" }
}

/// Dispatcher wrapper for [`schedule_exam`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_schedule_exam<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: ScheduleExamCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(ExamSchedule, ExamScheduled)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            schedule_exam::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for GenerateSeatPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.generateSeatPlan.generate" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "generate" }
    fn target_type(&self) -> &'static str { "generateSeatPlan" }
}

/// Dispatcher wrapper for [`generate_seat_plan`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_generate_seat_plan<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: GenerateSeatPlanCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(SeatPlan, SeatPlanGenerated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            generate_seat_plan::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for GenerateAdmitCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.generateAdmitCard.generate" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "generate" }
    fn target_type(&self) -> &'static str { "generateAdmitCard" }
}

/// Dispatcher wrapper for [`generate_admit_card`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_generate_admit_card<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: GenerateAdmitCardCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(AdmitCard, AdmitCardGenerated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            generate_admit_card::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RegenerateAdmitCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.regenerateAdmitCard.regenerate" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "regenerate" }
    fn target_type(&self) -> &'static str { "regenerateAdmitCard" }
}

/// Dispatcher wrapper for [`regenerate_admit_card`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_regenerate_admit_card<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RegenerateAdmitCardCommand,
    clock: &C,
    ids: &G
) -> Result<Result<AdmitCardRegenerated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            regenerate_admit_card::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for InitializeMarksRegisterCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.initializeMarksRegister.initialize" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "initialize" }
    fn target_type(&self) -> &'static str { "initializeMarksRegister" }
}

/// Dispatcher wrapper for [`initialize_marks_register`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_initialize_marks_register<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: InitializeMarksRegisterCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(crate::aggregate::MarksRegister, MarksRegisterCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            initialize_marks_register::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for EnterMarksCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.enterMark.enter" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "enter" }
    fn target_type(&self) -> &'static str { "enterMark" }
}

/// Dispatcher wrapper for [`enter_marks`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_enter_marks<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: EnterMarksCommand,
    clock: &C,
    ids: &G
) -> Result<Result<MarksEntered>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            enter_marks::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for SubmitMarksCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.submitMark.submit" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "submit" }
    fn target_type(&self) -> &'static str { "submitMark" }
}

/// Dispatcher wrapper for [`submit_marks`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_submit_marks<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: SubmitMarksCommand,
    clock: &C,
    ids: &G
) -> Result<Result<MarksSubmitted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            submit_marks::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for SubmitMarksCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.submitMark.cancel" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "cancel" }
    fn target_type(&self) -> &'static str { "submitMark" }
}

/// Dispatcher wrapper for [`cancel_marks_register`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_cancel_marks_register<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: SubmitMarksCommand,
    clock: &C,
    ids: &G
) -> Result<Result<MarksRegisterCancelled>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            cancel_marks_register::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for PublishResultCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.publishResult.publish" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "publish" }
    fn target_type(&self) -> &'static str { "publishResult" }
}

/// Dispatcher wrapper for [`publish_result`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_publish_result<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: PublishResultCommand,
    clock: &C,
    ids: &G
) -> Result<Result<ResultPublished>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            publish_result::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RepublishResultCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.republishResult.republish" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "republish" }
    fn target_type(&self) -> &'static str { "republishResult" }
}

/// Dispatcher wrapper for [`republish_result`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_republish_result<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RepublishResultCommand,
    clock: &C,
    ids: &G
) -> Result<Result<ResultRepublished>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            republish_result::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateResultRemarksCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.resultRemark.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "resultRemark" }
}

/// Dispatcher wrapper for [`update_result_remarks`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_result_remarks<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateResultRemarksCommand,
    clock: &C,
    ids: &G
) -> Result<Result<ResultRemarksUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_result_remarks::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for GenerateReportCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.generateReportCard.generate" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "generate" }
    fn target_type(&self) -> &'static str { "generateReportCard" }
}

/// Dispatcher wrapper for [`generate_report_card`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_generate_report_card<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: GenerateReportCardCommand,
    clock: &C,
    ids: &G
) -> Result<Result<ReportCardGenerated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            generate_report_card::<C, G>(cmd)
        })
        .await
}

