// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/documents/src/commands.rs (10 commands)
//
// Each impl block derives action/target from the command name.
// Capability string is inferred from the crate path.
// Skip commands without a `tenant: TenantContext` field.
//
// Wire into domains/documents/src/commands.rs (append at end).
// Template: Wave 192 AdmitStudentCommand impl.

impl educore_dispatcher::CommandBounds for UploadFormCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.uploadForm.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "uploadForm" }
}

impl educore_dispatcher::CommandBounds for UpdateFormCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.form.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "form" }
}

impl educore_dispatcher::CommandBounds for DeleteFormCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.form.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "form" }
}

impl educore_dispatcher::CommandBounds for DispatchPostalCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.dispatchPostal.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "dispatchPostal" }
}

impl educore_dispatcher::CommandBounds for UpdatePostalDispatchCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.postalDispatch.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "postalDispatch" }
}

impl educore_dispatcher::CommandBounds for DeletePostalDispatchCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.postalDispatch.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "postalDispatch" }
}

impl educore_dispatcher::CommandBounds for ReceivePostalCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.receivePostal.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "receivePostal" }
}

impl educore_dispatcher::CommandBounds for UpdatePostalReceiveCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.postalReceive.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "postalReceive" }
}

impl educore_dispatcher::CommandBounds for DeletePostalReceiveCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.postalReceive.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "postalReceive" }
}

impl educore_dispatcher::CommandBounds for TrackPostalCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.trackPostal.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "trackPostal" }
}

// Generated: 10, Skipped (no tenant field): 0