// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/facilities/src/services.rs (15 fns)
//
// Add to domains/facilities/src/services.rs and domains/facilities/src/lib.rs.
// Template: Wave 192 dispatch_admit_student pattern.

use educore_dispatcher::CommandDispatcher;

impl educore_dispatcher::CommandBounds for crate::commands::CreateVehicleCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`create_vehicle`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_vehicle<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::CreateVehicleCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(Vehicle, VehicleCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_vehicle::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::CreateRouteCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`create_route`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_route<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::CreateRouteCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(crate::aggregate::Route, RouteCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_route::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::AssignVehicleToRouteCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`assign_vehicle_to_route`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_assign_vehicle_to_route<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::AssignVehicleToRouteCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(AssignVehicle, VehicleAssigned)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            assign_vehicle_to_route::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::CreateDormitoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`create_dormitory`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_dormitory<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::CreateDormitoryCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(Dormitory, DormitoryCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_dormitory::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::CreateRoomTypeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`create_room_type`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_room_type<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::CreateRoomTypeCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(RoomType, RoomTypeCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_room_type::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::CreateRoomCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`create_room`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_room<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::CreateRoomCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(Room, RoomCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_room::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::AssignStudentToRoomCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`assign_student_to_room`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_assign_student_to_room<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::AssignStudentToRoomCommand,
    clock: &C,
    ids: &G
) -> Result<Result<StudentAssignedToRoom>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            assign_student_to_room::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::CreateItemCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`create_item_category`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_item_category<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::CreateItemCategoryCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(crate::aggregate::ItemCategory, ItemCategoryCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_item_category::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::CreateItemCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`create_item`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_item<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::CreateItemCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(Item, ItemCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_item::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::CreateItemStoreCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`create_item_store`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_item_store<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::CreateItemStoreCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(ItemStore, ItemStoreCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_item_store::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::ReceiveItemCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.receive" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "receive" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`receive_item`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_receive_item<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::ReceiveItemCommand,
    clock: &C,
    ids: &G
) -> Result<Result<ReceiveItemResult>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            receive_item::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::IssueItemCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.issue" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "issue" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`issue_item`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_issue_item<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::IssueItemCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(ItemIssue, ItemIssued)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            issue_item::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::SellItemCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.sell" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "sell" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`sell_item`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_sell_item<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::SellItemCommand,
    clock: &C,
    ids: &G
) -> Result<Result<SellItemResult>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            sell_item::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::CreateSupplierCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`create_supplier`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_supplier<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::CreateSupplierCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(Supplier, SupplierCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_supplier::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for crate::commands::UnassignStudentFromRoomCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.unknown.unassign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unassign" }
    fn target_type(&self) -> &'static str { "unknown" }
}

/// Dispatcher wrapper for [`unassign_student_from_room`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_unassign_student_from_room<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: crate::commands::UnassignStudentFromRoomCommand,
    clock: &C,
    ids: &G
) -> Result<Result<crate::events::StudentUnassignedFromRoom>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            unassign_student_from_room::<C, G>(cmd)
        })
        .await
}

