// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/assessment/src/commands.rs (62 commands)
//
// Each impl block derives action/target from the command name.
// Capability string is inferred from the crate path.
// Skip commands without a `tenant: TenantContext` field.
//
// Wire into domains/assessment/src/commands.rs (append at end).
// Template: Wave 192 AdmitStudentCommand impl.

impl educore_dispatcher::CommandBounds for CreateExamCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.exam.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "exam" }
}

impl educore_dispatcher::CommandBounds for UpdateExamCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.exam.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "exam" }
}

impl educore_dispatcher::CommandBounds for DeleteExamCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.exam.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "exam" }
}

impl educore_dispatcher::CommandBounds for ScheduleExamCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.scheduleExam.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "scheduleExam" }
}

impl educore_dispatcher::CommandBounds for UpdateExamScheduleCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.examSchedule.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "examSchedule" }
}

impl educore_dispatcher::CommandBounds for CancelExamScheduleCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.examSchedule.cancel" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "cancel" }
    fn target_type(&self) -> &'static str { "examSchedule" }
}

impl educore_dispatcher::CommandBounds for GenerateSeatPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.generateSeatPlan.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "generateSeatPlan" }
}

impl educore_dispatcher::CommandBounds for UpdateSeatPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.seatPlan.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "seatPlan" }
}

impl educore_dispatcher::CommandBounds for CancelSeatPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.seatPlan.cancel" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "cancel" }
    fn target_type(&self) -> &'static str { "seatPlan" }
}

impl educore_dispatcher::CommandBounds for GenerateAdmitCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.generateAdmitCard.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "generateAdmitCard" }
}

impl educore_dispatcher::CommandBounds for RegenerateAdmitCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.regenerateAdmitCard.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "regenerateAdmitCard" }
}

impl educore_dispatcher::CommandBounds for CancelAdmitCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.admitCard.cancel" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "cancel" }
    fn target_type(&self) -> &'static str { "admitCard" }
}

impl educore_dispatcher::CommandBounds for InitializeMarksRegisterCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.initializeMarksRegister.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "initializeMarksRegister" }
}

impl educore_dispatcher::CommandBounds for EnterMarksCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.enterMark.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "enterMark" }
}

impl educore_dispatcher::CommandBounds for SubmitMarksCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.submitMark.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "submitMark" }
}

impl educore_dispatcher::CommandBounds for PublishResultCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.publishResult.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "publishResult" }
}

impl educore_dispatcher::CommandBounds for RepublishResultCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.republishResult.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "republishResult" }
}

impl educore_dispatcher::CommandBounds for UpdateResultRemarksCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.resultRemark.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "resultRemark" }
}

impl educore_dispatcher::CommandBounds for GenerateReportCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "assessment.generateReportCard.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "generateReportCard" }
}

// SKIP CreateMarksGradeCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateMarksGradeCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP DeleteMarksGradeCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateExamSettingCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateExamSettingCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP DeleteExamSettingCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP SetExamSignatureCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateExamSignatureCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP DeleteExamSignatureCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateExamRoutinePageCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP PublishExamRoutineCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP PublishFrontResultCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateFrontendExamResultCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateOnlineExamCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP PublishOnlineExamCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP StartOnlineExamCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP SubmitOnlineExamAnswerCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP EvaluateOnlineExamCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateQuestionCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateQuestionCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP DeleteQuestionCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateQuestionGroupCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateQuestionGroupCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP DeleteQuestionGroupCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateQuestionLevelCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateQuestionLevelCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP DeleteQuestionLevelCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP ConfigureAdmitCardSettingsCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP MarkTeacherEvaluationCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP ApproveTeacherEvaluationCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RejectTeacherEvaluationCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP AddTeacherRemarkCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateTeacherRemarkCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP ConfigureCustomResultSettingsCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP MarkExamStepSkipCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP MarkExamAttendanceCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateExamAttendanceCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateExamTypeCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP UpdateExamTypeCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP DeleteExamTypeCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP ConfigureSeatPlanSettingsCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP ConfigureTeacherEvaluationCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RequestAbsenceNotificationCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// Generated: 19, Skipped (no tenant field): 43