// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/academic/src/services.rs (58 fns)
//
// Add to domains/academic/src/services.rs and domains/academic/src/lib.rs.
// Template: Wave 192 dispatch_admit_student pattern.

use educore_dispatcher::CommandDispatcher;

impl educore_dispatcher::CommandBounds for AdmitStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.student.admit" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "admit" }
    fn target_type(&self) -> &'static str { "student" }
}

/// Dispatcher wrapper for [`admit_student`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_admit_student<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AdmitStudentCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(Student, StudentAdmitted)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            admit_student::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateClassCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.class.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "class" }
}

/// Dispatcher wrapper for [`create_class`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_class<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateClassCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(Class, ClassCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_class::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateSectionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.section.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "section" }
}

/// Dispatcher wrapper for [`create_section`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_section<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateSectionCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(Section, SectionCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_section::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateSubjectCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.subject.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "subject" }
}

/// Dispatcher wrapper for [`create_subject`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_subject<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateSubjectCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(Subject, SubjectCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_subject::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateAcademicYearCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.academicYear.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "academicYear" }
}

/// Dispatcher wrapper for [`create_academic_year`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_academic_year<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateAcademicYearCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(AcademicYear, AcademicYearCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_academic_year::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RegisterGuardianCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.guardian.register" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "register" }
    fn target_type(&self) -> &'static str { "guardian" }
}

/// Dispatcher wrapper for [`register_guardian`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_register_guardian<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RegisterGuardianCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(Guardian, GuardianRegistered)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            register_guardian::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for LinkGuardianToStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.guardianToStudent.link" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "link" }
    fn target_type(&self) -> &'static str { "guardianToStudent" }
}

/// Dispatcher wrapper for [`link_guardian_to_student`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_link_guardian_to_student<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: LinkGuardianToStudentCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(StudentGuardianLink, GuardianLinkedToStudent)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            link_guardian_to_student::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AssignOptionalSubjectCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.optionalSubject.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "optionalSubject" }
}

/// Dispatcher wrapper for [`assign_optional_subject`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_assign_optional_subject<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AssignOptionalSubjectCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(OptionalSubjectAssignment, OptionalSubjectAssignmentCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            assign_optional_subject::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateClassSectionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.classSection.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "classSection" }
}

/// Dispatcher wrapper for [`create_class_section`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_class_section<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateClassSectionCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(ClassSection, ClassSectionCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_class_section::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AssignClassTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.classTeacher.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "classTeacher" }
}

/// Dispatcher wrapper for [`assign_class_teacher`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_assign_class_teacher<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AssignClassTeacherCommand,
    clock: &C,
    ids: &G
) -> Result<Result<ClassTeacherAssigned>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            assign_class_teacher::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AssignSubjectTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.subjectTeacher.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "subjectTeacher" }
}

/// Dispatcher wrapper for [`assign_subject_teacher`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_assign_subject_teacher<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AssignSubjectTeacherCommand,
    clock: &C,
    ids: &G
) -> Result<Result<SubjectTeacherAssigned>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            assign_subject_teacher::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AssignClassRoomCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.classRoom.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "classRoom" }
}

/// Dispatcher wrapper for [`assign_class_room`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_assign_class_room<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AssignClassRoomCommand,
    clock: &C,
    ids: &G
) -> Result<Result<ClassRoomAssigned>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            assign_class_room::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteClassSectionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.classSection.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "classSection" }
}

/// Dispatcher wrapper for [`delete_class_section`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_class_section<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteClassSectionCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<ClassSectionDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_class_section::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AssignSubjectToClassCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.subjectToClass.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "subjectToClass" }
}

/// Dispatcher wrapper for [`assign_subject_to_class`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_assign_subject_to_class<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AssignSubjectToClassCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(ClassSubject, SubjectAssignedToClass)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            assign_subject_to_class::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AssignSubjectToClassCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.subjectToClass.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "subjectToClass" }
}

/// Dispatcher wrapper for [`create_class_subject`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_class_subject<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AssignSubjectToClassCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(ClassSubject, SubjectAssignedToClass)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_class_subject::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for ReassignTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.teacher.reassign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "reassign" }
    fn target_type(&self) -> &'static str { "teacher" }
}

/// Dispatcher wrapper for [`reassign_teacher`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_reassign_teacher<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: ReassignTeacherCommand,
    clock: &C,
    ids: &G
) -> Result<Result<TeacherReassigned>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            reassign_teacher::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UnassignSubjectCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.subject.unassign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unassign" }
    fn target_type(&self) -> &'static str { "subject" }
}

/// Dispatcher wrapper for [`unassign_subject`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_unassign_subject<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UnassignSubjectCommand,
    clock: &C,
    ids: &G
) -> Result<Result<SubjectUnassigned>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            unassign_subject::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateClassRoutineCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.classRoutine.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "classRoutine" }
}

/// Dispatcher wrapper for [`create_class_routine`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_class_routine<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateClassRoutineCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(ClassRoutine, ClassRoutineScheduled)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_class_routine::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateClassRoutinePeriodCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.classRoutinePeriod.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "classRoutinePeriod" }
}

/// Dispatcher wrapper for [`update_class_routine_period`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_class_routine_period<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateClassRoutinePeriodCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<ClassRoutinePeriodUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_class_routine_period::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for SwapClassRoutinePeriodsCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.classRoutinePeriod.swap" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "swap" }
    fn target_type(&self) -> &'static str { "classRoutinePeriod" }
}

/// Dispatcher wrapper for [`swap_class_routine_periods`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_swap_class_routine_periods<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: SwapClassRoutinePeriodsCommand,
    clock: &C,
    ids: &G
) -> Result<Result<ClassRoutinePeriodsSwapped>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            swap_class_routine_periods::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteClassRoutineCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.classRoutine.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "classRoutine" }
}

/// Dispatcher wrapper for [`delete_class_routine`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_class_routine<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteClassRoutineCommand,
    clock: &C,
    ids: &G
) -> Result<Result<ClassRoutineDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_class_routine::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateHomeworkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.homework.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "homework" }
}

/// Dispatcher wrapper for [`create_homework`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_homework<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateHomeworkCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(Homework, HomeworkCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_homework::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateHomeworkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.homework.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "homework" }
}

/// Dispatcher wrapper for [`update_homework`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_homework<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateHomeworkCommand,
    clock: &C,
    ids: &G
) -> Result<Result<HomeworkUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_homework::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CancelHomeworkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.homework.cancel" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "cancel" }
    fn target_type(&self) -> &'static str { "homework" }
}

/// Dispatcher wrapper for [`cancel_homework`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_cancel_homework<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CancelHomeworkCommand,
    clock: &C,
    ids: &G
) -> Result<Result<HomeworkCancelled>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            cancel_homework::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RealCreateLessonPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.realCreateLessonPlan.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "realCreateLessonPlan" }
}

/// Dispatcher wrapper for [`create_lesson_plan`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_lesson_plan<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RealCreateLessonPlanCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(RealLessonPlan, RealLessonPlanCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_lesson_plan::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateLessonPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.lessonPlan.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "lessonPlan" }
}

/// Dispatcher wrapper for [`update_lesson_plan`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_lesson_plan<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateLessonPlanCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LessonPlanUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_lesson_plan::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for MarkLessonPlanCompletedCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.lessonPlanCompleted.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "lessonPlanCompleted" }
}

/// Dispatcher wrapper for [`mark_lesson_plan_completed`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_mark_lesson_plan_completed<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: MarkLessonPlanCompletedCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LessonPlanCompleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            mark_lesson_plan_completed::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AddSubTopicCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.addSubTopic.add" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "add" }
    fn target_type(&self) -> &'static str { "addSubTopic" }
}

/// Dispatcher wrapper for [`add_sub_topic`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_add_sub_topic<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AddSubTopicCommand,
    clock: &C,
    ids: &G
) -> Result<Result<SubTopicAdded>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            add_sub_topic::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteLessonPlanCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.lessonPlan.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "lessonPlan" }
}

/// Dispatcher wrapper for [`delete_lesson_plan`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_lesson_plan<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteLessonPlanCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LessonPlanDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_lesson_plan::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RealCreateLessonCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.realCreateLesson.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "realCreateLesson" }
}

/// Dispatcher wrapper for [`create_lesson`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_lesson<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RealCreateLessonCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(RealLesson, RealLessonCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_lesson::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateLessonCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.lesson.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "lesson" }
}

/// Dispatcher wrapper for [`update_lesson`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_lesson<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateLessonCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<LessonUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_lesson::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteLessonCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.lesson.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "lesson" }
}

/// Dispatcher wrapper for [`delete_lesson`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_lesson<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteLessonCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LessonDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_lesson::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RealCreateLessonTopicCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.realCreateLessonTopic.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "realCreateLessonTopic" }
}

/// Dispatcher wrapper for [`create_lesson_topic`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_lesson_topic<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RealCreateLessonTopicCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(RealLessonTopic, RealLessonTopicCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_lesson_topic::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for MarkTopicCompletedCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.topicCompleted.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "topicCompleted" }
}

/// Dispatcher wrapper for [`mark_topic_completed`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_mark_topic_completed<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: MarkTopicCompletedCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LessonTopicCompleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            mark_topic_completed::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteLessonTopicCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.lessonTopic.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "lessonTopic" }
}

/// Dispatcher wrapper for [`delete_lesson_topic`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_lesson_topic<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteLessonTopicCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LessonTopicDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_lesson_topic::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RecordStudentPromotionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.recordStudentPromotion.record" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "record" }
    fn target_type(&self) -> &'static str { "recordStudentPromotion" }
}

/// Dispatcher wrapper for [`record_student_promotion`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_record_student_promotion<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RecordStudentPromotionCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StudentPromotion, StudentPromotionRecorded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            record_student_promotion::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateStudentGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.studentGroup.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "studentGroup" }
}

/// Dispatcher wrapper for [`create_student_group`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_student_group<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateStudentGroupCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StudentGroup, StudentGroupCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_student_group::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RealCreateCertificateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.realCreateCertificate.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "realCreateCertificate" }
}

/// Dispatcher wrapper for [`create_certificate_aggregate`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_certificate_aggregate<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RealCreateCertificateCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(RealCertificate, RealCertificateCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_certificate_aggregate::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateCertificateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.certificate.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "certificate" }
}

/// Dispatcher wrapper for [`update_certificate`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_certificate<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateCertificateCommand,
    clock: &C,
    ids: &G
) -> Result<Result<CertificateUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_certificate::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteCertificateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.certificate.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "certificate" }
}

/// Dispatcher wrapper for [`delete_certificate`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_certificate<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteCertificateCommand,
    clock: &C,
    ids: &G
) -> Result<Result<CertificateDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_certificate::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RealCreateIdCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.realCreateIdCard.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "realCreateIdCard" }
}

/// Dispatcher wrapper for [`create_id_card_aggregate`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_id_card_aggregate<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RealCreateIdCardCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(RealIdCard, RealIdCardCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_id_card_aggregate::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateIdCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.idCard.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "idCard" }
}

/// Dispatcher wrapper for [`update_id_card`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_id_card<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateIdCardCommand,
    clock: &C,
    ids: &G
) -> Result<Result<IdCardUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_id_card::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteIdCardCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.idCard.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "idCard" }
}

/// Dispatcher wrapper for [`delete_id_card`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_id_card<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteIdCardCommand,
    clock: &C,
    ids: &G
) -> Result<Result<IdCardDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_id_card::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for EnrollStudentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.enrollStudent.enroll" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "enroll" }
    fn target_type(&self) -> &'static str { "enrollStudent" }
}

/// Dispatcher wrapper for [`enroll_student`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_enroll_student<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: EnrollStudentCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(StudentRecord, StudentRecordEnrolled)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            enroll_student::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for SetRollNumberCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.rollNumber.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "rollNumber" }
}

/// Dispatcher wrapper for [`set_roll_number`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_set_roll_number<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: SetRollNumberCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<RollNumberAssigned>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            set_roll_number::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for SetDefaultRecordCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.defaultRecord.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "defaultRecord" }
}

/// Dispatcher wrapper for [`set_default_record`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_set_default_record<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: SetDefaultRecordCommand,
    clock: &C,
    ids: &G
) -> Result<Result<DefaultRecordSet>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            set_default_record::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for MarkGraduateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.graduate.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "graduate" }
}

/// Dispatcher wrapper for [`mark_graduate`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_mark_graduate<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: MarkGraduateCommand,
    clock: &C,
    ids: &G
) -> Result<Result<StudentMarkedGraduate>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            mark_graduate::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RealCreateStudentCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.realCreateStudentCategory.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "realCreateStudentCategory" }
}

/// Dispatcher wrapper for [`create_student_category_aggregate`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_student_category_aggregate<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RealCreateStudentCategoryCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(RealStudentCategory, RealStudentCategoryCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_student_category_aggregate::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateStudentCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.studentCategory.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "studentCategory" }
}

/// Dispatcher wrapper for [`update_student_category`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_student_category<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateStudentCategoryCommand,
    clock: &C,
    ids: &G
) -> Result<Result<StudentCategoryUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_student_category::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteStudentCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.studentCategory.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "studentCategory" }
}

/// Dispatcher wrapper for [`delete_student_category`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_student_category<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteStudentCategoryCommand,
    clock: &C,
    ids: &G
) -> Result<Result<StudentCategoryDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_student_category::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RealCreateStudentGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.realCreateStudentGroup.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "realCreateStudentGroup" }
}

/// Dispatcher wrapper for [`create_student_group_aggregate`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_student_group_aggregate<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RealCreateStudentGroupCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(RealStudentGroup, RealStudentGroupCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_student_group_aggregate::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateStudentGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.studentGroup.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "studentGroup" }
}

/// Dispatcher wrapper for [`update_student_group`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_student_group<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateStudentGroupCommand,
    clock: &C,
    ids: &G
) -> Result<Result<StudentGroupUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_student_group::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AddStudentToGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.addStudentToGroup.add" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "add" }
    fn target_type(&self) -> &'static str { "addStudentToGroup" }
}

/// Dispatcher wrapper for [`add_student_to_group`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_add_student_to_group<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AddStudentToGroupCommand,
    clock: &C,
    ids: &G
) -> Result<Result<StudentAddedToGroup>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            add_student_to_group::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RemoveStudentFromGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.removeStudentFromGroup.remove" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "remove" }
    fn target_type(&self) -> &'static str { "removeStudentFromGroup" }
}

/// Dispatcher wrapper for [`remove_student_from_group`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_remove_student_from_group<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RemoveStudentFromGroupCommand,
    clock: &C,
    ids: &G
) -> Result<Result<StudentRemovedFromGroup>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            remove_student_from_group::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteStudentGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.studentGroup.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "studentGroup" }
}

/// Dispatcher wrapper for [`delete_student_group`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_student_group<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteStudentGroupCommand,
    clock: &C,
    ids: &G
) -> Result<Result<StudentGroupDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_student_group::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RealCreateRegistrationFieldCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.realCreateRegistrationField.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "realCreateRegistrationField" }
}

/// Dispatcher wrapper for [`create_registration_field_aggregate`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_registration_field_aggregate<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RealCreateRegistrationFieldCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(RealRegistrationField, RealRegistrationFieldCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_registration_field_aggregate::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateRegistrationFieldCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.registrationField.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "registrationField" }
}

/// Dispatcher wrapper for [`update_registration_field`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_registration_field<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateRegistrationFieldCommand,
    clock: &C,
    ids: &G
) -> Result<Result<RegistrationFieldUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_registration_field::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteRegistrationFieldCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.registrationField.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "registrationField" }
}

/// Dispatcher wrapper for [`delete_registration_field`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_registration_field<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteRegistrationFieldCommand,
    clock: &C,
    ids: &G
) -> Result<Result<RegistrationFieldDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_registration_field::<C, G>(cmd)
        })
        .await
}

