// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/hr/src/commands.rs (65 commands)
//
// Each impl block derives action/target from the command name.
// Capability string is inferred from the crate path.
// Skip commands without a `tenant: TenantContext` field.
//
// Wire into domains/hr/src/commands.rs (append at end).
// Template: Wave 192 AdmitStudentCommand impl.

impl educore_dispatcher::CommandBounds for SuspendStaffCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staff.suspend" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "suspend" }
    fn target_type(&self) -> &'static str { "staff" }
}

impl educore_dispatcher::CommandBounds for ChangeStaffDepartmentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.changeStaffDepartment.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "changeStaffDepartment" }
}

impl educore_dispatcher::CommandBounds for ChangeStaffDesignationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.changeStaffDesignation.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "changeStaffDesignation" }
}

impl educore_dispatcher::CommandBounds for ChangeStaffRoleCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.changeStaffRole.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "changeStaffRole" }
}

impl educore_dispatcher::CommandBounds for DeleteStaffCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staff.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "staff" }
}

impl educore_dispatcher::CommandBounds for RejectLeaveCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.leave.reject" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "reject" }
    fn target_type(&self) -> &'static str { "leave" }
}

impl educore_dispatcher::CommandBounds for CancelLeaveCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.leave.cancel" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "cancel" }
    fn target_type(&self) -> &'static str { "leave" }
}

impl educore_dispatcher::CommandBounds for MarkStaffAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staffAttendance.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "staffAttendance" }
}

impl educore_dispatcher::CommandBounds for ApprovePayrollCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.payroll.approve" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "approve" }
    fn target_type(&self) -> &'static str { "payroll" }
}

impl educore_dispatcher::CommandBounds for MarkPayrollPaidCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.payrollPaid.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "payrollPaid" }
}

impl educore_dispatcher::CommandBounds for AssignClassTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.classTeacher.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "classTeacher" }
}

impl educore_dispatcher::CommandBounds for DeleteAssignClassTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.assignClassTeacher.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "assignClassTeacher" }
}

impl educore_dispatcher::CommandBounds for SetHourlyRateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.hourlyRate.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "hourlyRate" }
}

impl educore_dispatcher::CommandBounds for CreateSalaryTemplateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.salaryTemplate.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "salaryTemplate" }
}

impl educore_dispatcher::CommandBounds for CreateStaffRegistrationFieldCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staffRegistrationField.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "staffRegistrationField" }
}

impl educore_dispatcher::CommandBounds for CreateDepartmentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.department.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "department" }
}

impl educore_dispatcher::CommandBounds for DeleteDepartmentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.department.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "department" }
}

impl educore_dispatcher::CommandBounds for DeleteDesignationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.designation.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "designation" }
}

impl educore_dispatcher::CommandBounds for DeleteLeaveTypeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.leaveType.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "leaveType" }
}

impl educore_dispatcher::CommandBounds for CreateDesignationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.designation.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "designation" }
}

impl educore_dispatcher::CommandBounds for CreateLeaveTypeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.leaveType.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "leaveType" }
}

impl educore_dispatcher::CommandBounds for ApproveLeaveCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.leave.approve" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "approve" }
    fn target_type(&self) -> &'static str { "leave" }
}

impl educore_dispatcher::CommandBounds for DefineLeavePolicyCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.defineLeavePolicy.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "defineLeavePolicy" }
}

impl educore_dispatcher::CommandBounds for ImportStaffBulkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.importStaffBulk.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "importStaffBulk" }
}

// SKIP CreateStaffBankDetailCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateStaffAddressCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateStaffSocialLinkCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateStaffDocumentCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RefreshStaffTimelineCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP SetStaffCustomFieldCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RefreshStaffLeaveBalanceCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RecordLeaveRequestApprovalCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreatePayrollPaymentLinkCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RecordStaffImportResolutionCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RecordStaffPayrollHistoryCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RecordStaffLeaveHistoryCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateAssignClassTeacherScopeCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP AssignDepartmentHeadCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateDesignationGradeCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP SetHourlyRateOverrideCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateLeaveDefineAdjustmentCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateLeaveRequestAttachmentCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RecordStaffAttendancePunchCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP RecordPayrollGenerateAuditCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP AssignStaffRoleCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateStaffProfilePhotoCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateStaffDrivingLicenseCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateStaffRegistrationFieldOptionCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateBulkImportJobCommand: no `tenant: TenantContext` field (CommandBounds requires one)

// SKIP CreateStaffAttendanceImportBatchCommand: no `tenant: TenantContext` field (CommandBounds requires one)

impl educore_dispatcher::CommandBounds for RegisterStaffCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staff.register" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "register" }
    fn target_type(&self) -> &'static str { "staff" }
}

impl educore_dispatcher::CommandBounds for UpdateStaffCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staff.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "staff" }
}

impl educore_dispatcher::CommandBounds for UpdateAssignClassTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.assignClassTeacher.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "assignClassTeacher" }
}

impl educore_dispatcher::CommandBounds for ImportStaffAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.importStaffAttendance.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "importStaffAttendance" }
}

impl educore_dispatcher::CommandBounds for PromoteStaffAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staffAttendance.promote" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "promote" }
    fn target_type(&self) -> &'static str { "staffAttendance" }
}

impl educore_dispatcher::CommandBounds for RejectStaffAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staffAttendance.reject" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "reject" }
    fn target_type(&self) -> &'static str { "staffAttendance" }
}

impl educore_dispatcher::CommandBounds for GeneratePayrollCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.generatePayroll.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "generatePayroll" }
}

impl educore_dispatcher::CommandBounds for UpdatePayrollAmountsCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.payrollAmount.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "payrollAmount" }
}

impl educore_dispatcher::CommandBounds for AddPayrollEarningCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.addPayrollEarning.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "addPayrollEarning" }
}

impl educore_dispatcher::CommandBounds for AddPayrollDeductionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.addPayrollDeduction.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "addPayrollDeduction" }
}

impl educore_dispatcher::CommandBounds for AddLeaveDeductionInfoCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.addLeaveDeductionInfo.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "addLeaveDeductionInfo" }
}

impl educore_dispatcher::CommandBounds for PromoteStaffImportCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staffImport.promote" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "promote" }
    fn target_type(&self) -> &'static str { "staffImport" }
}

impl educore_dispatcher::CommandBounds for RejectStaffImportCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.staffImport.reject" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "reject" }
    fn target_type(&self) -> &'static str { "staffImport" }
}

impl educore_dispatcher::CommandBounds for AssignSubjectTeacherCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.subjectTeacher.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "subjectTeacher" }
}

impl educore_dispatcher::CommandBounds for RequestLeaveCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "hr.leave.request" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "request" }
    fn target_type(&self) -> &'static str { "leave" }
}

// Generated: 39, Skipped (no tenant field): 26