// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/hr/src/services.rs (29 fns)
//
// Add to domains/hr/src/services.rs and domains/hr/src/lib.rs.
// Template: Wave 192 dispatch_admit_student pattern.

use educore_dispatcher::CommandDispatcher;

impl educore_dispatcher::CommandBounds for HireStaffCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.hireStaff.hire" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "hire" }
    fn target_type(&self) -> &'static str { "hireStaff" }
}

/// Dispatcher wrapper for [`hire_staff`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_hire_staff<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: HireStaffCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(Staff, StaffRegistered)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            hire_staff::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RequestLeaveCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.requestLeave.request" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "request" }
    fn target_type(&self) -> &'static str { "requestLeave" }
}

/// Dispatcher wrapper for [`request_leave`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_request_leave<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RequestLeaveCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(LeaveRequest, LeaveRequested)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            request_leave::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RunPayrollCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.runPayroll.run" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "run" }
    fn target_type(&self) -> &'static str { "runPayroll" }
}

/// Dispatcher wrapper for [`run_payroll`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_run_payroll<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RunPayrollCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(PayrollGenerate, PayrollGenerated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            run_payroll::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateStaffBankDetailCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffBankDetail.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "staffBankDetail" }
}

/// Dispatcher wrapper for [`create_staff_bank_detail`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_staff_bank_detail<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateStaffBankDetailCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffBankDetail, StaffBankDetailUpserted)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_staff_bank_detail::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateStaffAddressCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffAddress.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "staffAddress" }
}

/// Dispatcher wrapper for [`create_staff_address`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_staff_address<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateStaffAddressCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffAddress, StaffAddressAdded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_staff_address::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateStaffSocialLinkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffSocialLink.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "staffSocialLink" }
}

/// Dispatcher wrapper for [`create_staff_social_link`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_staff_social_link<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateStaffSocialLinkCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffSocialLink, StaffSocialLinkAdded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_staff_social_link::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateStaffDocumentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffDocument.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "staffDocument" }
}

/// Dispatcher wrapper for [`create_staff_document`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_staff_document<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateStaffDocumentCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffDocument, StaffDocumentRegistered)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_staff_document::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RefreshStaffTimelineCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.refreshStaffTimeline.refresh" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "refresh" }
    fn target_type(&self) -> &'static str { "refreshStaffTimeline" }
}

/// Dispatcher wrapper for [`refresh_staff_timeline`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_refresh_staff_timeline<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RefreshStaffTimelineCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffTimeline, StaffTimelineRefreshed)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            refresh_staff_timeline::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for SetStaffCustomFieldCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffCustomField.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "staffCustomField" }
}

/// Dispatcher wrapper for [`set_staff_custom_field`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_set_staff_custom_field<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: SetStaffCustomFieldCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffCustomField, StaffCustomFieldSet)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            set_staff_custom_field::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RefreshStaffLeaveBalanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.refreshStaffLeaveBalance.refresh" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "refresh" }
    fn target_type(&self) -> &'static str { "refreshStaffLeaveBalance" }
}

/// Dispatcher wrapper for [`refresh_staff_leave_balance`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_refresh_staff_leave_balance<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RefreshStaffLeaveBalanceCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffLeaveBalance, StaffLeaveBalanceRefreshed)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            refresh_staff_leave_balance::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RecordLeaveRequestApprovalCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.recordLeaveRequestApproval.record" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "record" }
    fn target_type(&self) -> &'static str { "recordLeaveRequestApproval" }
}

/// Dispatcher wrapper for [`record_leave_request_approval`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_record_leave_request_approval<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RecordLeaveRequestApprovalCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(LeaveRequestApproval, LeaveRequestApprovalRecorded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            record_leave_request_approval::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreatePayrollPaymentLinkCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.payrollPaymentLink.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "payrollPaymentLink" }
}

/// Dispatcher wrapper for [`create_payroll_payment_link`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_payroll_payment_link<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreatePayrollPaymentLinkCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(PayrollPaymentLink, PayrollPaymentLinkCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_payroll_payment_link::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RecordStaffImportResolutionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.recordStaffImportResolution.record" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "record" }
    fn target_type(&self) -> &'static str { "recordStaffImportResolution" }
}

/// Dispatcher wrapper for [`record_staff_import_resolution`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_record_staff_import_resolution<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RecordStaffImportResolutionCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffImportResolution, StaffImportResolutionRecorded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            record_staff_import_resolution::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RecordStaffPayrollHistoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.recordStaffPayrollHistory.record" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "record" }
    fn target_type(&self) -> &'static str { "recordStaffPayrollHistory" }
}

/// Dispatcher wrapper for [`record_staff_payroll_history`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_record_staff_payroll_history<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RecordStaffPayrollHistoryCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffPayrollHistory, StaffPayrollHistorySnapshotted)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            record_staff_payroll_history::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RecordStaffLeaveHistoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.recordStaffLeaveHistory.record" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "record" }
    fn target_type(&self) -> &'static str { "recordStaffLeaveHistory" }
}

/// Dispatcher wrapper for [`record_staff_leave_history`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_record_staff_leave_history<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RecordStaffLeaveHistoryCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffLeaveHistory, StaffLeaveHistorySnapshotted)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            record_staff_leave_history::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateAssignClassTeacherScopeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.assignClassTeacherScope.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "assignClassTeacherScope" }
}

/// Dispatcher wrapper for [`create_assign_class_teacher_scope`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_assign_class_teacher_scope<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateAssignClassTeacherScopeCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(AssignClassTeacherScope, AssignClassTeacherScopeAdded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_assign_class_teacher_scope::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AssignDepartmentHeadCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.departmentHead.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "departmentHead" }
}

/// Dispatcher wrapper for [`assign_department_head`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_assign_department_head<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AssignDepartmentHeadCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(DepartmentHead, DepartmentHeadRecorded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            assign_department_head::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateDesignationGradeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.designationGrade.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "designationGrade" }
}

/// Dispatcher wrapper for [`create_designation_grade`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_designation_grade<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateDesignationGradeCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(DesignationGrade, DesignationGradeRecorded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_designation_grade::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for SetHourlyRateOverrideCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.hourlyRateOverride.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "hourlyRateOverride" }
}

/// Dispatcher wrapper for [`set_hourly_rate_override`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_set_hourly_rate_override<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: SetHourlyRateOverrideCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(HourlyRateOverride, HourlyRateOverrideSet)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            set_hourly_rate_override::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateLeaveDefineAdjustmentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.leaveDefineAdjustment.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "leaveDefineAdjustment" }
}

/// Dispatcher wrapper for [`create_leave_define_adjustment`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_leave_define_adjustment<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateLeaveDefineAdjustmentCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(LeaveDefineAdjustment, LeaveDefineAdjustmentApplied)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_leave_define_adjustment::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateLeaveRequestAttachmentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.leaveRequestAttachment.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "leaveRequestAttachment" }
}

/// Dispatcher wrapper for [`create_leave_request_attachment`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_leave_request_attachment<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateLeaveRequestAttachmentCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(LeaveRequestAttachment, LeaveRequestAttachmentRegistered)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_leave_request_attachment::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RecordStaffAttendancePunchCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.recordStaffAttendancePunch.record" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "record" }
    fn target_type(&self) -> &'static str { "recordStaffAttendancePunch" }
}

/// Dispatcher wrapper for [`record_staff_attendance_punch`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_record_staff_attendance_punch<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RecordStaffAttendancePunchCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffAttendancePunch, StaffAttendancePunchCaptured)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            record_staff_attendance_punch::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RecordPayrollGenerateAuditCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.recordPayrollGenerateAudit.record" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "record" }
    fn target_type(&self) -> &'static str { "recordPayrollGenerateAudit" }
}

/// Dispatcher wrapper for [`record_payroll_generate_audit`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_record_payroll_generate_audit<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RecordPayrollGenerateAuditCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(PayrollGenerateAudit, PayrollGenerateAuditAppended)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            record_payroll_generate_audit::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AssignStaffRoleCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffRole.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "staffRole" }
}

/// Dispatcher wrapper for [`assign_staff_role`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_assign_staff_role<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AssignStaffRoleCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffRoleAssignment, StaffRoleAssignmentRecorded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            assign_staff_role::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateStaffProfilePhotoCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffProfilePhoto.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "staffProfilePhoto" }
}

/// Dispatcher wrapper for [`create_staff_profile_photo`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_staff_profile_photo<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateStaffProfilePhotoCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffProfilePhoto, StaffProfilePhotoRegistered)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_staff_profile_photo::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateStaffDrivingLicenseCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffDrivingLicense.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "staffDrivingLicense" }
}

/// Dispatcher wrapper for [`create_staff_driving_license`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_staff_driving_license<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateStaffDrivingLicenseCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(StaffDrivingLicense, StaffDrivingLicenseRegistered)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_staff_driving_license::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateStaffRegistrationFieldOptionCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffRegistrationFieldOption.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "staffRegistrationFieldOption" }
}

/// Dispatcher wrapper for [`create_staff_registration_field_option`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_staff_registration_field_option<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateStaffRegistrationFieldOptionCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(
    StaffRegistrationFieldOption,
    StaffRegistrationFieldOptionAdded,
)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_staff_registration_field_option::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateBulkImportJobCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.bulkImportJob.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "bulkImportJob" }
}

/// Dispatcher wrapper for [`create_bulk_import_job`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_bulk_import_job<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateBulkImportJobCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(BulkImportJob, BulkImportJobRecorded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_bulk_import_job::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CreateStaffAttendanceImportBatchCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffAttendanceImportBatch.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "staffAttendanceImportBatch" }
}

/// Dispatcher wrapper for [`create_staff_attendance_import_batch`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_staff_attendance_import_batch<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateStaffAttendanceImportBatchCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(
    StaffAttendanceImportBatch,
    StaffAttendanceImportBatchRecorded,
)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_staff_attendance_import_batch::<C, G>(cmd)
        })
        .await
}

