// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/communication/src/commands.rs (72 commands)
//
// Each impl block derives action/target from the command name.
// Capability string is inferred from the crate path.
// Skip commands without a `tenant: TenantContext` field.
//
// Wire into domains/communication/src/commands.rs (append at end).
// Template: Wave 192 AdmitStudentCommand impl.

impl educore_dispatcher::CommandBounds for CreateNoticeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.notice.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "notice" }
}

impl educore_dispatcher::CommandBounds for UpdateNoticeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.notice.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "notice" }
}

impl educore_dispatcher::CommandBounds for PublishNoticeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.publishNotice.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "publishNotice" }
}

impl educore_dispatcher::CommandBounds for UnpublishNoticeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.unpublishNotice.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "unpublishNotice" }
}

impl educore_dispatcher::CommandBounds for DeleteNoticeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.notice.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "notice" }
}

impl educore_dispatcher::CommandBounds for RegisterComplaintCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.complaint.register" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "register" }
    fn target_type(&self) -> &'static str { "complaint" }
}

impl educore_dispatcher::CommandBounds for AssignComplaintCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.complaint.assign" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "assign" }
    fn target_type(&self) -> &'static str { "complaint" }
}

impl educore_dispatcher::CommandBounds for UpdateComplaintStatusCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.complaintStatu.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "complaintStatu" }
}

impl educore_dispatcher::CommandBounds for ResolveComplaintCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.resolveComplaint.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "resolveComplaint" }
}

impl educore_dispatcher::CommandBounds for AddComplaintNoteCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.addComplaintNote.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "addComplaintNote" }
}

impl educore_dispatcher::CommandBounds for CreateComplaintTypeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.complaintType.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "complaintType" }
}

impl educore_dispatcher::CommandBounds for UpdateComplaintTypeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.complaintType.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "complaintType" }
}

impl educore_dispatcher::CommandBounds for DeleteComplaintTypeCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.complaintType.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "complaintType" }
}

impl educore_dispatcher::CommandBounds for SendNotificationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.sendNotification.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "sendNotification" }
}

impl educore_dispatcher::CommandBounds for MarkNotificationReadCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.notificationRead.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "notificationRead" }
}

impl educore_dispatcher::CommandBounds for WithdrawNotificationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.notification.withdraw" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "withdraw" }
    fn target_type(&self) -> &'static str { "notification" }
}

impl educore_dispatcher::CommandBounds for LogEmailSentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.logEmailSent.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "logEmailSent" }
}

impl educore_dispatcher::CommandBounds for LogSmsSentCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.logSmsSent.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "logSmsSent" }
}

impl educore_dispatcher::CommandBounds for CreateSmsTemplateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.smsTemplate.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "smsTemplate" }
}

impl educore_dispatcher::CommandBounds for UpdateSmsTemplateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.smsTemplate.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "smsTemplate" }
}

impl educore_dispatcher::CommandBounds for EnableSmsTemplateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.enableSmsTemplate.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "enableSmsTemplate" }
}

impl educore_dispatcher::CommandBounds for DisableSmsTemplateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.disableSmsTemplate.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "disableSmsTemplate" }
}

impl educore_dispatcher::CommandBounds for DeleteSmsTemplateCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.smsTemplate.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "smsTemplate" }
}

impl educore_dispatcher::CommandBounds for ConfigureEmailSettingCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.configureEmailSetting.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "configureEmailSetting" }
}

impl educore_dispatcher::CommandBounds for ActivateEmailSettingCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.activateEmailSetting.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "activateEmailSetting" }
}

impl educore_dispatcher::CommandBounds for DeleteEmailSettingCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.emailSetting.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "emailSetting" }
}

impl educore_dispatcher::CommandBounds for ConfigureSmsGatewayCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.configureSmsGateway.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "configureSmsGateway" }
}

impl educore_dispatcher::CommandBounds for ActivateSmsGatewayCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.activateSmsGateway.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "activateSmsGateway" }
}

impl educore_dispatcher::CommandBounds for DeleteSmsGatewayCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.smsGateway.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "smsGateway" }
}

impl educore_dispatcher::CommandBounds for CreateCustomSmsSettingCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.customSmsSetting.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "customSmsSetting" }
}

impl educore_dispatcher::CommandBounds for UpdateCustomSmsSettingCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.customSmsSetting.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "customSmsSetting" }
}

impl educore_dispatcher::CommandBounds for DeleteCustomSmsSettingCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.customSmsSetting.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "customSmsSetting" }
}

impl educore_dispatcher::CommandBounds for CreateNotificationSettingCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.notificationSetting.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "notificationSetting" }
}

impl educore_dispatcher::CommandBounds for UpdateNotificationSettingCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.notificationSetting.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "notificationSetting" }
}

impl educore_dispatcher::CommandBounds for DeleteNotificationSettingCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.notificationSetting.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "notificationSetting" }
}

impl educore_dispatcher::CommandBounds for ConfigureAbsentNotificationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.configureAbsentNotification.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "configureAbsentNotification" }
}

impl educore_dispatcher::CommandBounds for EnableAbsentNotificationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.enableAbsentNotification.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "enableAbsentNotification" }
}

impl educore_dispatcher::CommandBounds for DisableAbsentNotificationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.disableAbsentNotification.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "disableAbsentNotification" }
}

impl educore_dispatcher::CommandBounds for DeleteAbsentNotificationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.absentNotification.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "absentNotification" }
}

impl educore_dispatcher::CommandBounds for OpenChatConversationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatConversation.open" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "open" }
    fn target_type(&self) -> &'static str { "chatConversation" }
}

impl educore_dispatcher::CommandBounds for CloseChatConversationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatConversation.close" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "close" }
    fn target_type(&self) -> &'static str { "chatConversation" }
}

impl educore_dispatcher::CommandBounds for SendChatMessageCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.sendChatMessage.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "sendChatMessage" }
}

impl educore_dispatcher::CommandBounds for MarkChatMessageSeenCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatMessageSeen.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "chatMessageSeen" }
}

impl educore_dispatcher::CommandBounds for DeleteChatMessageCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatMessage.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "chatMessage" }
}

impl educore_dispatcher::CommandBounds for CreateChatGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatGroup.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "chatGroup" }
}

impl educore_dispatcher::CommandBounds for UpdateChatGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatGroup.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "chatGroup" }
}

impl educore_dispatcher::CommandBounds for SetChatGroupReadOnlyCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatGroupReadOnly.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "chatGroupReadOnly" }
}

impl educore_dispatcher::CommandBounds for DeleteChatGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatGroup.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "chatGroup" }
}

impl educore_dispatcher::CommandBounds for AddUserToChatGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.addUserToChatGroup.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "addUserToChatGroup" }
}

impl educore_dispatcher::CommandBounds for SetChatGroupUserRoleCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatGroupUserRole.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "chatGroupUserRole" }
}

impl educore_dispatcher::CommandBounds for RemoveUserFromChatGroupCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.removeUserFromChatGroup.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "removeUserFromChatGroup" }
}

impl educore_dispatcher::CommandBounds for RecordGroupMessageRecipientCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.recordGroupMessageRecipient.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "recordGroupMessageRecipient" }
}

impl educore_dispatcher::CommandBounds for MarkGroupMessageReadCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.groupMessageRead.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "groupMessageRead" }
}

impl educore_dispatcher::CommandBounds for RemoveGroupMessageForUserCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.removeGroupMessageForUser.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "removeGroupMessageForUser" }
}

impl educore_dispatcher::CommandBounds for BlockUserCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.blockUser.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "blockUser" }
}

impl educore_dispatcher::CommandBounds for UnblockUserCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.unblockUser.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "unblockUser" }
}

impl educore_dispatcher::CommandBounds for SendChatInvitationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.sendChatInvitation.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "sendChatInvitation" }
}

impl educore_dispatcher::CommandBounds for AcceptChatInvitationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.acceptChatInvitation.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "acceptChatInvitation" }
}

impl educore_dispatcher::CommandBounds for RejectChatInvitationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatInvitation.reject" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "reject" }
    fn target_type(&self) -> &'static str { "chatInvitation" }
}

impl educore_dispatcher::CommandBounds for ClassifyChatInvitationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.classifyChatInvitation.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "classifyChatInvitation" }
}

impl educore_dispatcher::CommandBounds for SetChatStatusCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.chatStatu.set" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "set" }
    fn target_type(&self) -> &'static str { "chatStatu" }
}

impl educore_dispatcher::CommandBounds for CreateSendMessageCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.sendMessage.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "sendMessage" }
}

impl educore_dispatcher::CommandBounds for DispatchSendMessageCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.dispatchSendMessage.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "dispatchSendMessage" }
}

impl educore_dispatcher::CommandBounds for CancelSendMessageCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.sendMessage.cancel" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "cancel" }
    fn target_type(&self) -> &'static str { "sendMessage" }
}

impl educore_dispatcher::CommandBounds for ReceiveContactMessageCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.receiveContactMessage.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "receiveContactMessage" }
}

impl educore_dispatcher::CommandBounds for MarkContactMessageViewedCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.contactMessageViewed.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "contactMessageViewed" }
}

impl educore_dispatcher::CommandBounds for ReplyToContactMessageCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.replyToContactMessage.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "replyToContactMessage" }
}

impl educore_dispatcher::CommandBounds for CreateSpeechSliderCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.speechSlider.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "speechSlider" }
}

impl educore_dispatcher::CommandBounds for UpdateSpeechSliderCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.speechSlider.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "speechSlider" }
}

impl educore_dispatcher::CommandBounds for DeleteSpeechSliderCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.speechSlider.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "speechSlider" }
}

impl educore_dispatcher::CommandBounds for LogPhoneCallCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.logPhoneCall.unknown" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "unknown" }
    fn target_type(&self) -> &'static str { "logPhoneCall" }
}

impl educore_dispatcher::CommandBounds for UpdatePhoneCallFollowUpCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "unknown.phoneCallFollowUp.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "phoneCallFollowUp" }
}

// Generated: 72, Skipped (no tenant field): 0