// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/attendance/src/services.rs (7 fns)
//
// Add to domains/attendance/src/services.rs and domains/attendance/src/lib.rs.
// Template: Wave 192 dispatch_admit_student pattern.

use educore_dispatcher::CommandDispatcher;

impl educore_dispatcher::CommandBounds for MarkStudentAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.studentAttendance.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "studentAttendance" }
}

/// Dispatcher wrapper for [`mark_student_attendance`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_mark_student_attendance<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: MarkStudentAttendanceCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(StudentAttendance, StudentAttendanceMarked)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            mark_student_attendance::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for BulkMarkStudentAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.bulkMarkStudentAttendance.bulk" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "bulk" }
    fn target_type(&self) -> &'static str { "bulkMarkStudentAttendance" }
}

/// Dispatcher wrapper for [`bulk_mark_student_attendance`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_bulk_mark_student_attendance<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: BulkMarkStudentAttendanceCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<BulkMarkResult>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            bulk_mark_student_attendance::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for MarkSubjectAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.subjectAttendance.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "subjectAttendance" }
}

/// Dispatcher wrapper for [`mark_subject_attendance`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_mark_subject_attendance<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: MarkSubjectAttendanceCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(SubjectAttendance, SubjectAttendanceMarked)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            mark_subject_attendance::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for MarkStaffAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.staffAttendance.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "staffAttendance" }
}

/// Dispatcher wrapper for [`mark_staff_attendance`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_mark_staff_attendance<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: MarkStaffAttendanceCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(StaffAttendance, StaffAttendanceMarked)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            mark_staff_attendance::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for MarkExamAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.examAttendance.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "examAttendance" }
}

/// Dispatcher wrapper for [`mark_exam_attendance`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_mark_exam_attendance<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: MarkExamAttendanceCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(ExamAttendance, ExamAttendanceMarked)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            mark_exam_attendance::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for ImportAttendanceCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.importAttendance.import" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "import" }
    fn target_type(&self) -> &'static str { "importAttendance" }
}

/// Dispatcher wrapper for [`import_attendance`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_import_attendance<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: ImportAttendanceCommand,
    clock: &C,
    ids: &G,
    uniqueness: &dyn UniquenessChecker,
) -> Result<Result<(
    BulkAttendanceImport,
    Vec<StudentAttendanceImport>,
    BulkImportStarted,
)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            import_attendance::<C, G>(cmd,
        uniqueness,)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RequestAbsenceNotificationCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.requestAbsenceNotification.request" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "request" }
    fn target_type(&self) -> &'static str { "requestAbsenceNotification" }
}

/// Dispatcher wrapper for [`request_absence_notification`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_request_absence_notification<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RequestAbsenceNotificationCommand,
    clock: &C,
    ids: &G
) -> Result<Result<AbsenceNotificationRequested>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            request_absence_notification::<C, G>(cmd)
        })
        .await
}

