// AUTO-GENERATED by tools/dispatcher-gen/dispatcher-gen.py
// Source: domains/library/src/services.rs (22 fns)
//
// Add to domains/library/src/services.rs and domains/library/src/lib.rs.
// Template: Wave 192 dispatch_admit_student pattern.

use educore_dispatcher::CommandDispatcher;

impl educore_dispatcher::CommandBounds for CreateBookCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.bookCategory.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "bookCategory" }
}

/// Dispatcher wrapper for [`create_book_category`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_book_category<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CreateBookCategoryCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(BookCategory, BookCategoryCreated)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_book_category::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AddBookCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.addBook.add" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "add" }
    fn target_type(&self) -> &'static str { "addBook" }
}

/// Dispatcher wrapper for [`add_book`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_add_book<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AddBookCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(Book, BookAdded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            add_book::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RegisterLibraryMemberCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.libraryMember.register" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "register" }
    fn target_type(&self) -> &'static str { "libraryMember" }
}

/// Dispatcher wrapper for [`register_library_member`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_register_library_member<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RegisterLibraryMemberCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(LibraryMember, LibraryMemberRegistered)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            register_library_member::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for IssueBookCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.issueBook.create" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "create" }
    fn target_type(&self) -> &'static str { "issueBook" }
}

/// Dispatcher wrapper for [`create_book_issue`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_create_book_issue<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: IssueBookCommand,
    clock: &C,
    ids: &G
) -> Result<Result<BookIssueCreated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            create_book_issue::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for ReturnBookCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.returnBook.return" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "return" }
    fn target_type(&self) -> &'static str { "returnBook" }
}

/// Dispatcher wrapper for [`return_book`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_return_book<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: ReturnBookCommand,
    clock: &C,
    ids: &G
) -> Result<Result<BookReturnResult>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            return_book::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for CalculateFineCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.calculateFine.compute" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "compute" }
    fn target_type(&self) -> &'static str { "calculateFine" }
}

/// Dispatcher wrapper for [`compute_fine`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_compute_fine<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: CalculateFineCommand,
    clock: &C,
    ids: &G
) -> Result<Result<FineComputed>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            compute_fine::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateBookCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.bookCategory.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "bookCategory" }
}

/// Dispatcher wrapper for [`update_book_category`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_book_category<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateBookCategoryCommand,
    clock: &C,
    ids: &G
) -> Result<Result<BookCategoryUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_book_category::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteBookCategoryCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.bookCategory.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "bookCategory" }
}

/// Dispatcher wrapper for [`delete_book_category`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_book_category<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteBookCategoryCommand,
    clock: &C,
    ids: &G
) -> Result<Result<BookCategoryDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_book_category::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateBookCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.book.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "book" }
}

/// Dispatcher wrapper for [`update_book`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_book<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateBookCommand,
    clock: &C,
    ids: &G
) -> Result<Result<BookUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_book::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteBookCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.book.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "book" }
}

/// Dispatcher wrapper for [`delete_book`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_book<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteBookCommand,
    clock: &C,
    ids: &G
) -> Result<Result<BookDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_book::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for AdjustBookQuantityCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.adjustBookQuantity.adjust" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "adjust" }
    fn target_type(&self) -> &'static str { "adjustBookQuantity" }
}

/// Dispatcher wrapper for [`adjust_book_quantity`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_adjust_book_quantity<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: AdjustBookQuantityCommand,
    clock: &C,
    ids: &G
) -> Result<Result<BookQuantityAdjusted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            adjust_book_quantity::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for UpdateLibraryMemberCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.libraryMember.update" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "update" }
    fn target_type(&self) -> &'static str { "libraryMember" }
}

/// Dispatcher wrapper for [`update_library_member`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_update_library_member<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: UpdateLibraryMemberCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LibraryMemberUpdated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            update_library_member::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeactivateLibraryMemberCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.deactivateLibraryMember.deactivate" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "deactivate" }
    fn target_type(&self) -> &'static str { "deactivateLibraryMember" }
}

/// Dispatcher wrapper for [`deactivate_library_member`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_deactivate_library_member<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeactivateLibraryMemberCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LibraryMemberDeactivated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            deactivate_library_member::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for ReactivateLibraryMemberCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.reactivateLibraryMember.reactivate" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "reactivate" }
    fn target_type(&self) -> &'static str { "reactivateLibraryMember" }
}

/// Dispatcher wrapper for [`reactivate_library_member`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_reactivate_library_member<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: ReactivateLibraryMemberCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LibraryMemberReactivated>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            reactivate_library_member::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for DeleteLibraryMemberCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.libraryMember.delete" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "delete" }
    fn target_type(&self) -> &'static str { "libraryMember" }
}

/// Dispatcher wrapper for [`delete_library_member`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_delete_library_member<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: DeleteLibraryMemberCommand,
    clock: &C,
    ids: &G
) -> Result<Result<LibraryMemberDeleted>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            delete_library_member::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RenewBookCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.book.renew" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "renew" }
    fn target_type(&self) -> &'static str { "book" }
}

/// Dispatcher wrapper for [`renew_book`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_renew_book<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RenewBookCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(BookIssue, BookRenewed)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            renew_book::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for MarkBookLostCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.bookLost.mark" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "mark" }
    fn target_type(&self) -> &'static str { "bookLost" }
}

/// Dispatcher wrapper for [`mark_book_lost`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_mark_book_lost<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: MarkBookLostCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(BookIssue, BookMarkedLost)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            mark_book_lost::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for RecordBookReturnCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.recordBookReturn.record" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "record" }
    fn target_type(&self) -> &'static str { "recordBookReturn" }
}

/// Dispatcher wrapper for [`record_book_return`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_record_book_return<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: RecordBookReturnCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(BookReturn, BookReturnRecorded)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            record_book_return::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for WaiveBookIssueFineCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.waiveBookIssueFine.waive" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "waive" }
    fn target_type(&self) -> &'static str { "waiveBookIssueFine" }
}

/// Dispatcher wrapper for [`waive_book_issue_fine`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_waive_book_issue_fine<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: WaiveBookIssueFineCommand,
    clock: &C,
    ids: &G
) -> Result<Result<(Fine, FineWaived)>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            waive_book_issue_fine::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for SearchBooksCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.searchBook.search" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "search" }
    fn target_type(&self) -> &'static str { "searchBook" }
}

/// Dispatcher wrapper for [`search_books`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_search_books<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: SearchBooksCommand,
    clock: &C,
    ids: &G
) -> Result<Result<Vec<Book>>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            search_books::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for ListOverdueIssuesCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.listOverdueIssu.list" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "list" }
    fn target_type(&self) -> &'static str { "listOverdueIssu" }
}

/// Dispatcher wrapper for [`list_overdue_issues`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_list_overdue_issues<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: ListOverdueIssuesCommand,
    clock: &C,
    ids: &G
) -> Result<Result<Vec<BookIssue>>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            list_overdue_issues::<C, G>(cmd)
        })
        .await
}


impl educore_dispatcher::CommandBounds for ListMemberIssuesCommand {
    fn tenant(&self) -> &TenantContext { &self.tenant }
    fn command_type(&self) -> &'static str { "<domain>.listMemberIssu.list" }
    fn idempotency_key(&self) -> Option<IdempotencyKey> { None }
    fn action(&self) -> &'static str { "list" }
    fn target_type(&self) -> &'static str { "listMemberIssu" }
}

/// Dispatcher wrapper for [`list_member_issues`].
///
/// Mirrors the Wave 192 template: clones `cmd` inside the closure
/// to satisfy the borrow checker, then runs the full
/// `CommandDispatcher::dispatch` pipeline (RBAC → txn →
/// idempotency → service → outbox → audit → idempotency record
/// → bus publish).
pub async fn dispatch_list_member_issues<C, G>(
    dispatcher: &CommandDispatcher,
    cmd: ListMemberIssuesCommand,
    clock: &C,
    ids: &G
) -> Result<Result<Vec<BookIssue>>
where
    C: Clock + ?Sized,
    G: IdGenerator + ?Sized,>
where
    C: Clock + ?Sized + Send + Sync,
    G: IdGenerator + ?Sized + Send + Sync,
{
    use educore_dispatcher::CommandBounds as _;
    dispatcher
        .dispatch(&cmd, &["<capability>"], || async {
            list_member_issues::<C, G>(cmd)
        })
        .await
}

